### ISSUE TITLE
import-error and no-name-in-module for importing an object defined in a private module in a private package

### ISSUE THREAD

**Issue by vtgn** [pylint-dev/pylint#10068]
### Question

Hi!

I try to use private packages (folders prefixed by _) and modules (files prefixed by _).
If I import an object defined in the private module, Pylint generates the import-error and the no-name-in-module errors.
The problem is not present if the package or the module is not private.

```py
from project._pkg._module import MyClass # 2 Pylint errors (see below)

from project._pkg.module import MyClass # OK

from project.pkg._module import MyClass # OK
```
> Unable to import 'project._pkg._module' Pylint(E0401:import-error)

> No name '_module' in module 'project._pkg' Pylint(E0611:no-name-in-module)

Is it normal? I don't find this behavior consistent between these 3 cases. Plus these 2 error messages are poorly clear for such case.

Thanks.
Regards.

### Documentation for future user

If it is normal, a better error with a better description should be used.

### Additional context

From Microsoft Pylint vscode extension v2024.0.0. Version of pylint: pylint=3.2.7

**Comment by mbyrnepr2** [comment]
I can't reproduce this one. Maybe something different with your project structure?

```python
(venv312) markbyrne@Marks-Air-2 project % tree
.
├── mytest.py
├── project
│   ├── _pkg
│   │   ├── _module.py
│   │   └── module.py
│   └── pkg
│       └── _module.py
└── pyproject.toml

3 directories, 5 files

(venv312) markbyrne@Marks-Air-2 project % cat mytest.py 
from project._pkg._module import tomato
tomato()

from project._pkg.module import tomato
tomato()

from project.pkg._module import tomato
tomato()
(venv312) markbyrne@Marks-Air-2 project % 
```

**Comment by vtgn** [comment]
It seems restarting the extension fixes the problem. I forgot to try it. Sorry. :/
