### ISSUE TITLE
Checker `async.py` couldn't be imported anywhere because it uses reserved word.

### ISSUE THREAD

**Issue by bgb10** [pylint-dev/pylint#10071]
### Current problem

Wanted to make test code for async checkers, but since name of async checker is async.py, AsyncChecker class in this file cannot be imported anywhere. ('async' is keyword!) Indeed, we imported this nowhere before (just registered checker to linter as below), but to write test code for AsyncChecker, file rename is must.

### Desired solution

So renamed `async.py` to `async_checker.py`. 

### Additional context

PR: https://github.com/pylint-dev/pylint/pull/10060

**Comment by bgb10** [comment]
I created PR at first, and made this to write changelog 😄

**Comment by Pierre-Sassoulas** [comment]
Thank you. You can refs the pull request directly next time :)
