### ISSUE TITLE
Remove explicit test dependency on yanked package

### ISSUE THREAD

**Issue by jacobtylerwalls** [pylint-dev/pylint#10117]
see [logs](https://github.com/pylint-dev/pylint/actions/runs/12217752537/job/34082406105) in "Create python virtual environment" step

WARNING: The candidate selected for download or install is a yanked version: 'types-pkg-resources' candidate (version 0.1.3 at https://files.pythonhosted.org/packages/e9/97/a24ffd614ac2962dabbd599afbed00adf6464604a53b96b5f48301518a5f/types_pkg_resources-0.1.3-py2.py3-none-any.whl (from https://pypi.org/simple/types-pkg-resources/))
Reason for being yanked: Use types-setuptools instead

**Comment by Pierre-Sassoulas** [comment]
Nice catch!

**Comment by Pierre-Sassoulas** [comment]
It seems like it's due to a transitive dependency, I can't find the string anywhere in the codebase;

``grep -rH "types-pkg-resources" .``:
```
./tests/.pylint_primer_tests/home-assistant/core/requirements_test.txt:types-pkg-resources==0.1.3
```
``git grep -rH "types-pkg-resources" .``: nothing.

**Comment by jacobtylerwalls** [comment]
try types-pkg_resources with underscore
