### ISSUE TITLE
Compatibility with GPL3 / AGPL license

### ISSUE THREAD

**Issue by fhg-isi** [pylint-dev/pylint#10145]
### Current problem

Hello, could you please publish pylint under GPL 3 in addition to GPL 2?

Otherwise our Iegal department does not allow me to use pylint for our open source project due to license compatibility issues /unclarities. 

Many thanks for this great software. 

### Desired solution

Allow to use GPL 3 license.

**Comment by zenlyj** [comment]
Perhaps @Pierre-Sassoulas can give his opinion on this

**Comment by Pierre-Sassoulas** [comment]
No one contributing to pylint signed a CLA at any point, so it's near impossible to change the license in my opinion (need to ask everyone). (I'd bet at least some of the contributors are literally dead and I won't track their great nephew to retro-sign a NDA.) It might be a special case for gplv2 to v3 but it's still a lot of work to check that I could do that. I'd have to do a lot of explaining for a long time after that and it's a work I would not enjoy at all, so I won't do it except if someone else provide a very convincing legal justification that it's possible to do that.

That being said, I think that if you are using the linter as a standalone tool to analyze your code, this is not creating a derivative work of pylint. You are simply running the software, which is permitted under the GPL (any version as far as I know). Don't embed pylint in your own source code and you should be fine.

Also, it's not just me, Google is using pylint and did not release any of the code they linted (which is *all* their python code as far as I know).  

https://github.com/google/styleguide/blob/8f97e24da04753c7a15eda6b02114a01ec3146f5/pyguide.md?plain=1#L117

I guess that a reasonable assumption is that your legal department is worse at lawyering than Google legal department.

As an aside, Google even have[ a "highly customized" in-house version of pylint](https://news.ycombinator.com/item?id=40171125) and it seems no-one asked them for the source code yet. Guess pylint contributors are not very litigious.
