### ISSUE TITLE
Slow linting on edx/edx-platform

### ISSUE THREAD

**Issue by jcdyer** [pylint-dev/pylint#2545]
@PCManticore asked me to report a slow linting run to help you with testing performance work.  [edx/edx-platform](https://github.com/edx/edx-platform), a major open source MOOC, is a large codebase that takes a long time to complete a pylint run.  Hundreds of developers work on this codebase every day, so speeding up linting times would be a big win.

### Steps to reproduce

1.  `git clone https://github.com/edx/edx-platform`
2.  `cd edx-platform`
3.  `pip install -r requirements/test.txt`
4.  `time pylint lms`

    `lms` is about 50% of the entire codebase, but should be a sufficiently meaty example.

### Current behavior

Run completes in > 10 minutes.

### Expected behavior

Run completes in < 30 seconds. :crossed_fingers:  :grimacing: 

### pylint --version output

```sh
(edx-platform) cliff@conakry:~/edx-platform$ pip freeze|grep lint
edx-lint==0.5.5
pylint==1.7.1
pylint-celery==0.3
pylint-django==0.7.2
pylint-plugin-utils==0.3
```

**Comment by PCManticore** [comment]
Great stuff, thanks a lot! Also curious what's your astroid version?

**Comment by jcdyer** [comment]
Current versions are set here: https://github.com/edx/edx-lint/blob/master/requirements.txt

**Comment by Pierre-Sassoulas** [comment]
Maybe a project to add in the primer for #5359

**Comment by jacobtylerwalls** [comment]
Thanks for the info. 3.0 (thanks to improvements in astroid) will be dramatically faster. Let us know if you don't see a noticeable improvement.

On my M1 Mac, `time pylint lms` gives:
```
pylint lms  74.57s user 3.20s system 94% cpu 1:22.37 total
```
