### ISSUE TITLE
[feature] Being able to use stub ``pyi`` files in pylint

### ISSUE THREAD

**Issue by daltairwalter** [pylint-dev/pylint#4987]
### Bug description

I made some pyi files from pyd's using a stubgen program and I would like to use these pyi files for pylint.

I tried making some test cases with ``*.pyi`` files and they seem to be entirely ignored by pylint.  I searched for other issues related to pyi/stubs and there seemed to be a few issues, but none of them said these files were just flat out unused - so I am wondering if something else is going on.

This seems to work if I delete the *.pyd files and rename the *.pyi files to *.py.  Is this necessary?

When I import and use these files directly, there error messages are reasonably ignorable things like:

> UseLocation.py:3:7: I1101: Module 'pylintimportstar.RealLocation' has no 'RealClass' member, but source is unavailable. Consider adding this module to extension-pkg-allow-list if you want to perform analysis based on run-time introspection of living objects. (c-extension-no-member)

Unfortunately, when used through an import statement:
``from pylintimportstar.RealLocation import *``
The messages are all errors:
```
UseLocation.py:3:7: E1101: Module 'pylintimportstar' has no 'ReferenceLocation' member (no-member)
```

### Command used

```shell
C:\programs\anaconda3\Scripts\pylint.exe C:\test\pylintimportstar2\pylintimportstar
```

### Pylint output

```shell
************* Module ReferenceLocation
ReferenceLocation.py:1:0: C0304: Final newline missing (missing-final-newline)
ReferenceLocation.py:1:0: C0103: Module name "ReferenceLocation" doesn't conform to snake_case naming style (invalid-name)
ReferenceLocation.py:1:0: C0114: Missing module docstring (missing-module-docstring)
ReferenceLocation.py:1:0: W0401: Wildcard import pylintimportstar.RealLocation (wildcard-import)
************* Module UseLocation
UseLocation.py:4:0: C0304: Final newline missing (missing-final-newline)
UseLocation.py:1:0: C0103: Module name "UseLocation" doesn't conform to snake_case naming style (invalid-name)
UseLocation.py:1:0: C0114: Missing module docstring (missing-module-docstring)
UseLocation.py:3:7: E1101: Module 'pylintimportstar.ReferenceLocation' has no 'RealClass' member (no-member)
```

### Expected behavior

The error E1101 is not expected.

### Pylint version

```shell
pylint 2.10.2
astroid 2.7.3
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
```

Maintainer note: this was a duplicate of #2873 which has 11 👍 already so this is higher priority than it appear just by sorting by thumbsup.

**Comment by Pierre-Sassoulas** [comment]
I don't think anyone worked on it yet. I pinned the issue. Regarding the workaround [some options from the typechecker could help you](https://pylint.pycqa.org/en/latest/user_guide/checkers/features.html#typecheck-checker-options), in particular ``generated-members``.

**Comment by butla** [comment]
@Pierre-Sassoulas thanks for the tip with `generated-members`, it helped in my case.
Well, it didn't silence the `no-name-in-module` I had when doing `from <module> import <name>`. But when I changed the import to `import <module>` and started using qualified names in code (`<module>.<name>`), there were no errors.

**Comment by belm0** [comment]
`generated-members` is a poor workaround-- as mentioned it doesn't affect imports

**Comment by zs-dima** [comment]
Wow, 2 years and this issue still there

**Comment by zs-dima** [comment]
@Pierre-Sassoulas Sounds tempting, but there are more critical gRPC things that need fixing.

**Comment by simoncpu** [comment]
Greetings! I'm a time traveler from the year 2023, and I'm experiencing this problem as well.

**Comment by Pierre-Sassoulas** [comment]
It's fixed only on the main branch and not yet released, what version are you using ?

**Comment by idkw** [comment]
Could this change be backported to the 2.x branch ? Version 3.x is not yet released and this missing feature is a real blocker on the 2.x

**Comment by Pierre-Sassoulas** [comment]
There's an alpha of pylint 3.0.0 that is really stable if you want the fix right now (https://pypi.org/project/pylint/3.0.0a7/) and we're going to release 3.0.0b0 in days, and the actual 3.0.0 in a week for python 3.12 release.

**Comment by davetapley** [comment]
I'm seeing this with `pylint == 3.0.2` and `orjson==3.8.6`.

```
ng/asset/meta.py:6:0: E0611: No name 'JSONDecodeError' in module 'orjson' (no-name-in-module)
ng/asset/meta.py:6:0: E0611: No name 'loads' in module 'orjson' (no-name-in-module)
```

But: https://github.com/ijl/orjson/blob/3.9.6/pysrc/orjson/__init__.pyi#L11-L13

and I verified that file is in my `site-packages`, any ideas? 🤔

**Comment by jimmyzzxhlh** [comment]
I'm running into this issue for protobuf and pylint 3.0.2 is still not working, e.g.
`E0611: No name 'FloatValue' in module 'google.protobuf.wrappers_pb2' (no-name-in-module)`

Can we check if this is actually fixed?

**Comment by Pierre-Sassoulas** [comment]
Hello, thank you for reporting a problem, but please open a new issue, or your feedback is going to get lost in this closed issue.

**Comment by davetapley** [comment]
Missed this, but looks promising:
- https://github.com/pylint-dev/astroid/commit/12c3d1556be3bacaf4816898616b6124e0d44da9

I still feel like we need something to pass to `[tool.pylint.typecheck]` though, so it can know that the root is, something like PyRight's `stubPath`?
