### ISSUE TITLE
Cleanup after we drop support for Python 3.7

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [pylint-dev/pylint#6306]
When we do drop support because 3.7 has reached its end of life after 2023-06-27, we'll need to do some cleanup:

- [x] Remove the code for ``_ExtendAction`` (#8793)
- [x] Import ``Final``, ``Literal``, and ``TypedDict`` from typing directly
- [x] Remove ``functools.cached_property`` import guards

**Comment by cdce8p** [comment]
EOL for 3.7 is scheduled for `2023-06-27`.

Once 3.7 is dropped, the most notable changes for us are probably
* We can start using assignment expressions
* `Final`, `Literal`, `TypedDict` can be imported from `typing` directly
* We no longer need import guards for `functools.cached_property`

**Comment by Pierre-Sassoulas** [comment]
We also need to upgrade functional tests that are exclusive to python 3.7 so they use py-version instead.

**Comment by jacobtylerwalls** [comment]
> We also need to upgrade functional tests that are exclusive to python 3.7 so they use py-version instead.

For future reference, this was done when adjusting the `max_pyver` test setting, not the `min_pyver` setting. We discussed it [here](https://github.com/pylint-dev/pylint/pull/8811#discussion_r1248981435).
