### ISSUE TITLE
Uniformize ``compare-to-zero``, ``compare-to-empty-string`` with the ``use-implicit-booleaness-x`` checks

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [pylint-dev/pylint#6871]
### Current problem

 ``compare-to-zero`` and ``compare-to-empty-string`` are the same check basically than ``use-implicit-booleaness-not-copmparison``.  

Doing ``x != 0`` feel safer and easier to understand than ``bool(x)`` for int (you need a background in C to understand that). So``compare-to-zero`` feel more opinionated  which is probably why they are in their own optional checker. 

``compare-to-empty-string`` though is really an ``use-implicit-booleaness-not-copmparison`` check.  

### Desired solution

I think it would make sense to merge ``compare-to-empty-string`` . Renaming them so they all follow the same pattern could be an option.

### Additional context

https://github.com/PyCQA/pylint/pull/6861

I've done the work in #6870 then realized that ``compare-to-zero`` was opinionated.

**Comment by DanielNoord** [comment]
I think the `compare-to-zero` should stay an extension. Implicit booleanness of string does make sense to merge.
