### ISSUE TITLE
pyreverse: duplicates when using properties getters and setters

### ISSUE THREAD

**Issue by VasLem** [pylint-dev/pylint#7261]
I have a similar issue, using pylint 2.14.5 and Python 3.8 on this minimal example:
```
class Block:
    def __init__(self):
        self._cacheDir = None
    @property
    def cacheDir(self):
        if self._cacheDir is None:
            self.cacheDir = cacheDir
        return self._cacheDir

    @cacheDir.setter
    def cacheDir(self, value: str):
        self._cacheDir = value

```
I get this output:
![classes](https://user-images.githubusercontent.com/18720200/182590718-57fbfed4-15de-456e-a6a0-e66eefd5903f.png)

Is there a way to stop the duplicates from showing up or is this the expected behavior?

_Originally posted by @VasLem in https://github.com/PyCQA/pylint/issues/83#issuecomment-1203788403_

**Comment by clavedeluna** [comment]
This is due to these two lines:
```
        if self._cacheDir is None:
            self.cacheDir = cacheDir
```

removing them for testing makes the duplication go away.

**Comment by nickdrozd** [comment]
This was fixed by https://github.com/pylint-dev/pylint/pull/9004
