### ISSUE TITLE
Support catching multiple exceptions introduced in pep654 in python 3.11

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [pylint-dev/pylint#7703]
### Current problem

This new syntax is wrongly detected as a syntax error right now 

### Desired solution

Handle the new syntax.

### Additional context

https://docs.python.org/3.11/whatsnew/3.11.html#whatsnew311-pep654

**Comment by clavedeluna** [comment]
Spitballing here, but likely want to look into the exception grouping to be handled for the `broad-exception-raised` / `broad-exception-caught` messages.

**Comment by jacobtylerwalls** [comment]
Fixed in #2028
