### ISSUE TITLE
Add option to forcefully ignore inline disable messages for specified errors

### ISSUE THREAD

**Issue by ppiasek** [pylint-dev/pylint#8282]
### Current problem

We are having quite a big repository with plenty of contributors and sometimes # disable comments are needed in the code, but we don't want some of them to appear. For example we don't want "eval" to be used in code even, when "# pylint: disable=eval-used" comment is added. 

It would be nice to add option in config file / command line to enforce error checks for specified errors, even if disable comment is added.

### Desired solution

Lets say we have code like below:
`eval('print("eval-used")')  # pylint: disable=eval-used`

When I run pylint on that file, I won't get any error.

I'd like to run command like:
pylint --enforce-check=eval-used
so even though disable comment is used, I'll get error listed:

> ************* Module eval
> eval.py:1:0: W0123: Use of eval (eval-used)

**Comment by Pierre-Sassoulas** [comment]
A hack to get this feature would be to enable ``suppressed-message`` and then to ``|grep -c "eval-used"`` the result. Or to grep for ``# ?pylint: ?disable=[[\w\- ]*,? ?]*eval-used[\w-]?`` directly on the code. I'm not sure we should add this directly in pylint, the unwanted disable can be caught during review or another lighter tool  could catch the disable (Like https://github.com/Pierre-Sassoulas/black-disable-checker for black, or simply the previous regex and grep). The disable and message control are already complicated and powerful as is. This would be yet another perf decrease for a use case that I'm not sure a lot of person are going to have.

**Comment by nickdrozd** [comment]
It's wild that `eval` is provided to every single Python user right out of the box. It's potentially dangerous and drastically overpowered for virtually any application, and yet there it is, just floating around in the global namespace for everyone to use. It should at least be moved to `sys` or something like that.

Maybe `eval-used` could be marked as a critical check, such that disabling it requires extra work. For example, it can only be disabled via the config option `disable-eval-used-yes-i-know-what-im-doing`, or something like that.

I'm sure anyone who has a legitimate use for `eval` will understand and appreciate the extra diligence. Personally I've never seen a legitimate use for it in the wild, though I have seen several illegitimate uses.

**Comment by Pierre-Sassoulas** [comment]
> Maybe eval-used could be marked as a critical check, such that disabling it requires extra work

The maintenance burden of that would also be a lot of work for us 😄 If we ever do https://github.com/PyCQA/pylint/issues/5604 or the baseline #5403 then we could make this message one of the top priority messages to fix when it's disable. 

But mainly I think **teams** should be responsible for their disable. Pylint can't be the solution to a disagreement in your team. If a member is disabling eval-used the solution is to talk to the member about it, not add a super-enable in the conf instead (or soon your colleague will come to us and ask for a super-disable). 

I'm voting to close, let's see what other maintainers think.

**Comment by ppiasek** [comment]
> But mainly I think **teams** should be responsible for their disable. Pylint can't be the solution to a disagreement in your team. If a member is disabling eval-used the solution is to talk to the member about it, not add a super-enable in the conf instead (or soon your colleague will come to us and ask for a super-disable).

Yeah, but sometimes you know, it's a cultural difference in way people work and unfortunately, no matter how many times you mention some issues with their work, they are not heard at all. :C I know it's just a specific team issue, but in our case only few people are able to modify configs such as pylint one, so that solution would solve the issue. I understand, that most of the users won't have that kind of issues.

Anyway, thanks for replies. :)

**Comment by mbyrnepr2** [comment]
It's not what you are looking for but perhaps [bandit](https://bandit.readthedocs.io/en/1.7.4/blacklists/blacklist_calls.html#b307-eval) can be useful for this particular case; it indicates a medium severity when `eval` is used.

**Comment by ppiasek** [comment]
> It's not what you are looking for but perhaps [bandit](https://bandit.readthedocs.io/en/1.7.4/blacklists/blacklist_calls.html#b307-eval) can be useful for this particular case; it indicates a medium severity when `eval` is used.

Unfortunately, that's pretty much the same case. # nosec comment makes bandit to ignore errors without option to suppress that disable.

**Comment by Pierre-Sassoulas** [comment]
Closing as won't fix, pylint's pragmas should be discussed during code review : no amount of new option is going to prevent having to discuss disagreements about checks between team members.
