### ISSUE TITLE
Run only selected plugins

### ISSUE THREAD

**Issue by warvariuc** [pylint-dev/pylint#8557]
### Question

I have a custom plugin for pylint. Is it possible to run only it on the code?

### Documentation for future user

Probably there is no such functionality at all? `pylint --help` didn't show an option to do this.

**Comment by Pierre-Sassoulas** [comment]
You're right, there's no option for this. pylint's core checks (internal plugins) are supposed to run unless all their message are explicitly disabled in the ``disable=`` option and then they do nothing if they were properly optimized internally (the developer indicated that a visitor function was only useful for particular messages and those messages are disabled). So indirectly you could achieve that with ``disable=all enable=only-your-message lod-plugins=only.your.plugin``).
