### ISSUE TITLE
How to check file name convention?

### ISSUE THREAD

**Issue by stefaneidelloth** [pylint-dev/pylint#8569]
### Current problem

With eslint I can check the folder and file names to follow distinct file naming convention.

"folders/match-regex"

"filenames/match-regex", 

Is that also possible with pylint?

Also see

https://stackoverflow.com/questions/75995519/how-to-enforce-python-file-naming-convention

https://softwareengineering.stackexchange.com/questions/308972/python-file-naming-convention

### Desired solution

Please provide a rule to enforce snake_case naming convention for directories and file names.

**Comment by mbyrnepr2** [comment]
Hey @stefaneidelloth I think you're looking for the [invalid-name ](https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/invalid-name.html)checker.

snake_case is the default naming convention expected by Pylint; try it out by running Pylint on a module named `myModule.py` and it emits:
`myModule.py:1:0: C0103: Module name "myModule" doesn't conform to snake_case naming style (invalid-name)`.

Let me know if that answers your question and we can close the issue.

**Comment by stefaneidelloth** [comment]
Follow up: Is it possible to apply that rule to non-python files, too?

**Comment by mbyrnepr2** [comment]
> Follow up: Is it possible to apply that rule to non-python files, too?

Module and package names supported only according to the [docs](https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/invalid-name.html) @stefaneidelloth:


Name Type | Description
-- | --
module | Module and package names, same as the file names.
