### ISSUE TITLE
Not respecting type: ignore

### ISSUE THREAD

**Issue by dmail00** [pylint-dev/pylint#8593]
### Bug description

```
"""Issue with broad-exception-raised"""
def _f():
    raise Exception("foo")# pylint: disable=broad-exception-raised

def _fg():
    raise Exception("foo")# type: ignore

```
The disable directive is working yet type: ignore is ignored and produces the following.
`************* Module issue
issue.py:6:4: W0719: Raising too general exception: Exception (broad-exception-raised)`

### Command used

```shell
python -m pylint issue.py
```

### Pylint output

```shell
`************* Module issue
issue.py:6:4: W0719: Raising too general exception: Exception (broad-exception-raised)`
```

### Expected behavior

Regardless of if this is a too broad an exception, I use multiple versions of python and pylint and some versions of pylint are too old to understand the disable directive for the issue and therefore itself generates a warning about an unknown option. I was trying to make code compatible with the versions I use and trying to silence it via a type: ignore yet this is not respected in later pylint versions.

### Pylint version

```shell
Tested with 2.17.2, 3.0.0a6 and head
(.venv_head) I:\python\pylint_issue>pip show pylint
Name: pylint
Version: 3.0.0b1
Summary: python code static checker
Home-page: None
Author: None
Author-email: Python Code Quality Authority <code-quality@python.org>
License: GPL-2.0-or-later
Location: i:\python\pylint_issue\.venv_head\lib\site-packages
Requires: typing-extensions, colorama, tomli, platformdirs, mccabe, isort, dill, astroid, tomlkit
Required-by:
```

```
(.venv3.0.0a6) I:\python\pylint_issue>pip show pylint
Name: pylint
Version: 3.0.0a6
Summary: python code static checker
Home-page: None
Author: None
Author-email: Python Code Quality Authority <code-quality@python.org>
License: GPL-2.0-or-later
Location: i:\python\pylint_issue\pylint-3.0.0a6
Requires: platformdirs, astroid, isort, mccabe, tomlkit, typing-extensions, dill, tomli, colorama
Required-by:
```

```
(.venv2.17.2) I:\python\pylint_issue>pip show pylint
Name: pylint
Version: 2.17.2
Summary: python code static checker
Home-page: None
Author: None
Author-email: Python Code Quality Authority <code-quality@python.org>
License: GPL-2.0-or-later
Location: i:\python\pylint_issue\pylint-2.17.2
Requires: platformdirs, astroid, isort, mccabe, tomlkit, typing-extensions, dill, tomli, colorama
Required-by:
```
```


### OS / Environment

Windows 10

### Additional dependencies

_No response_

**Comment by DanielNoord** [comment]
`type: ignore` is a concept for type checkers. Since `pylint` is a linter we don't check for it!

**Comment by dmail00** [comment]
So is there a way to disable a check that is not available on an older version without itself generating a warning?

**Comment by dmail00** [comment]
> I wonder why you are running multiple versions of pylint

One reason is the following: https://github.com/pylint-dev/pylint/issues/7383
Another is that in some environments, I have no control of the version of libraries that are used.

**Comment by DanielNoord** [comment]
Hmm okay, yeah then I would advise adding an ignoring for the non existent option

**Comment by dmail00** [comment]
Thanks.
For any future readers, the disable bad option has to come before the specific option
`raise Exception("foo")  # pylint: disable=bad-option-value,broad-exception-raised`
