### ISSUE TITLE
Replace `consider-using-f-string` with `avoid-using-percent-string`

### ISSUE THREAD

**Issue by Mynotoar** [pylint-dev/pylint#8599]
### Current problem

The current `consider-using-f-string` warning I believe is inappropriately opinionated. Of the 3 most common ways of providing string interpolation in Python:

* `%` formatting - clearly inappropriate, Pylint is right to flag this and suggest you avoid its usage
* .format() string - Not always the best solution, but sometimes very readable, and good for embedding long variables or functions
* f-string - Perfectly acceptable under certain circumstances - becomes unwieldy when you have long variables or functions embedded in strings.

`consider-using-f-string` selects f-string as the only acceptable method, when there is a good reason to allow `.format()` strings as well.

[The Pylint doc for this warning](https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/consider-using-f-string.html) states states:

> "Used when we detect a string that is being formatted with format() or % which could potentially be an f-string. **The use of f-strings is preferred**."

and

> "Formatted string literals (f-strings) give a concise, consistent syntax **that can replace most use cases** for the % formatting operator, str.format() and string.Template."

(emphasis mine)

I disagree with the emphasised statements. Take the below example, where string.format() is a more readable choice than f-strings:

```python
percent_string = "The result of %s + %s is %s" % (
    a, b, some_long_complicated_function(a, b)
)

format_string = "The result of {} + {} is {}".format(
    a, b, some_long_complicated_function(a, b)
)

f_string = f"The result of {a} + {b} is {some_long_complicated_function(a, b)}"
```

I could waive this warning, but that's not the point - Pylint is meant to recommend best coding practices for Python. I do not believe that this is a best coding practice - f-strings are a good feature, but they are not appropriate for every solution. Pylint should not enforce the opinion that "f-strings are superior to format strings", because it's demonstrably incorrect.

### Desired solution

Deprecate the `consider-using-f-string` warning. Replace it with a warning that specifically targets the use of `%` string formatting. This type of formatting *is* much harder to read and should be highlighted by a linter. However format strings should not be flagged by the linter.

This warning could be called `avoid-using-percent-string`, and should probably be either a `Warning` or a `Convention`.

### Additional context

https://stackoverflow.com/questions/74600829/pylint-doesnt-like-string-format-and-wants-me-to-use-f-strings-is-this-fixab/76040925?noredirect=1#comment134146105_76040925

**Comment by DudeNr33** [comment]
I agree that the example as given is not very readable, but what is the problem with extracting a variable for the result of the computation?

```python
result = some_long_complicated_function(a, b)
f_string = f"The result of {a} + {b} is {result}"
```

**Comment by DanielNoord** [comment]
The point of the message is that `f-strings` are faster on most interpreters, although there are speed ups for other strings in the latest interpreter. Thus, it is not only about readability but about performance.

**Comment by Mynotoar** [comment]
Is it the role of a linter to highlight how you can optimise performance in Python? If it is then the premise of this warning is sound, but it's my understanding that lint is meant to catch examples of poor coding style and other bad practice.

**Comment by DanielNoord** [comment]
I think the end of your sentence is why this is a grey area. I think writing less performant code also falls within bad practice, unless it leads to completely unmaintainable or unreadable code. What that constitutes is always up for debate, but I think `f-strings` fit within the stuff a linter can optimize/recommend for.
This is also what we generally do with `consider-xxx` messages. They are a combination of style + performance suggestions. Just looking in our docs will show quite a couple of these.

**Comment by Mynotoar** [comment]
@DanielNoord You're right, it's a grey area. I think my issue with it is: the notion that "x is more performant than y therefore use x" trades off against the fact that sometimes you have a good reason to use x even if it's not as performant as y. If you're writing a program where [the difference between 78 ns and 283 ns](https://twitter.com/raymondh/status/1205969258800275456) is absolutely negligible or you're not concerned about micro-optimising performance, then a slight performance hit may be acceptable and even encouraged if the resulting code is more maintainable and easy to read.

Should Pylint be making those calls for you? I'd argue not - especially if Pylint is used to gate commits in continuous integration. Granted, this is a larger discussion than f-strings, but I'm not quibbling with the other `consider-` features you mention. My thought remains that enforcing f-strings in all scenarios because it's 1) more performant and 2) more readable falls down when 1) performance isn't a concern and 2) it's sometimes **less** readable than alternatives.

**Comment by Gouvernathor** [comment]
As for @DudeNr33's "use a local variable" solution, I'd add that it pollutes the namespace you're in and may hold up garbage collection for an unnecessary variable. I don't think the use of local variables should be advocated in general - except to improve readability which, in this case, .format is better at.

In my opinion though the almost 4x performance speedup is a good enough reason to keep issuing something when encountering a .format on a string litteral.

However, I'm not sure how it behaves now. Maybe the best solution would be to have that opt-out warning on .format and a different warning, more "serious", on %-interpolations ? Is that how things currently work ?

**Comment by mbyrnepr2** [comment]
Overall I feel the checker works as expected and echoes the rationale of PEP 498.
Firstly, the `additional details` of the [documentation](https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/consider-using-f-string.html) indicate that readability is the first concern and performance is the second concern of the checker:

_Formatted string literals (f-strings) give a concise, consistent syntax that can replace most use cases for the % formatting operator, str.format() and string.Template._

_F-strings also perform better than alternatives; see [this tweet](https://twitter.com/raymondh/status/1205969258800275456) for a simple example._

Secondly, If we take a look at [PEP498](https://peps.python.org/pep-0498), from a readability perspective, it says:

_However, str.format() is not without its issues. Chief among them is its verbosity. For example, the text value is repeated here:_

```python
>>> value = 4 * 20
>>> 'The value is {value}.'.format(value=value)
'The value is 80.'
```

_Even in its simplest form there is a bit of boilerplate, and the value that’s inserted into the placeholder is sometimes far removed from where the placeholder is situated:_

```python
>>> 'The value is {}.'.format(value)
'The value is 80.'
```

_With an f-string, this becomes:_

```python
>>> f'The value is {value}.'
'The value is 80.'
```

_F-strings provide a concise, readable way to include the value of Python expressions inside strings._

> Should Pylint be making those calls for you? I'd argue not - especially if Pylint is used to gate commits in continuous integration

One thing I would say about this is that the checker in question is a refactor suggestion - it's not meant to indicate a critical situation or _enforce_ anything. Pylint is configurable which means your team can silence this one (per-instance or globally) if it doesn't suit your team's wishes.

**Comment by Pierre-Sassoulas** [comment]
> Pylint should not enforce the opinion that "f-strings are superior to format strings", because it's demonstrably incorrect.

It's not a demonstration it's your stated opinion that some code is less readable than some other code, which is both a valid opinion and arguably not how everyone feel about this. Readability is not the only criteria that should be taken into account (performance and consistency being two major concerns of this check).  f-strings are demonstrably faster than ``format`` currently and the syntax is demonstrably terser too.

Caveat: We have some known use cases where ``consider-using-fstring`` could be disabled because it's known that the alternative is better performance wise (functional context see #8224).

> Is it the role of a linter to highlight how you can optimize performance in Python?

pylint check code syntax and formatting issues, outright errors, readability, code quality (unused variables, duplicated code), coding standards compliance (pep8, or things like ``no-else-return`` a mozilla opinionated code standard), even possible security vulnerabilities (bi-directional unicode) and yes, also performance issues (logging-not-lazy, use-a-generator, membership test are faster on set than on tuple, etc. etc.). 

> sometimes you have a good reason to use x even if it's not as performant as y. (...) a slight performance hit may be acceptable and even encouraged if the resulting code is more maintainable and easy to read.

pylint is not choosing for you. We have checks that tells you that something is better than something else (``use-a-generator`` is non opinionated for example) but when the message name start with ``consider-...`` it's something you'll have to consider 😄  pylint permit to enable/disable messages. You're the one who knows what's the aspect that is prevalent in your code base. 

I agree with @mbyrnepr2, I don't think we should change an existing message radically. If you don't like f-string, disable the check, if you like f-strings but only some of the time disable the check inline.

We could introduce a new message to favor format over ``%`` as an opinionated code standard extension, but I'm not personally going to invest time to implement this because consider-using-f-string covers it.

**Comment by mattbsage** [comment]
`consider-using-f-string`  is correct, IMVHO.

Not a fan of `format()`s extra verbosity - even for the use case stated in the OP as f-strings have an analog that has better readability and takes only a minor performance hit over a single f-string.

```
f_string_done_better = (
    f"The result of {a} + {b} is "
    f"{some_long_complicated_function(a, b)}"
)
```

This has the added "benefit" of being able to mix interpolated and non-interpolated strings in the same assignment - *i.e.* each sub-string can be evaluated independently by the linter.

**Comment by mbyrnepr2** [comment]
Thanks for the reminder @mattbsage  :). Thanks everyone. Let's reopen if anyone would like to discuss further.
