### ISSUE TITLE
deprecate collections.namedtuple in favor of dataclasses

### ISSUE THREAD

**Issue by vapier** [pylint-dev/pylint#8656]
### Current problem

when using Python 3.8+, collections.namedtuple is archaic, and should be flagged for upgrading

### Desired solution

when collections.namedtuple is seen, recommend using dataclasses instead

**Comment by DanielNoord** [comment]
There are still reasons to use a `NamedTuple` instead of a dataclass. We already have warning for using both, I don't think we should start recommending either.

See https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-namedtuple-or-dataclass.html

**Comment by Pierre-Sassoulas** [comment]
Agree with @DanielNoord. Surprisingly NamedTuple or bare class are faster than dataclass at least until 3.11 (because they have less auto-created magic method). I don't think we should push in favor of one or the other. (But untyped dict are pure evils of course).

**Comment by vapier** [comment]
this issue is about `collections.namedtuple`, not `typing.NamedTuple`

the `consider-using-namedtuple-or-dataclass` isn't about both being used, it's about suggesting anything-but-dict

**Comment by DanielNoord** [comment]
Yes, but like I said there are valid use cases for the tuple variant. For example, in a context where you want to iterate over the object over a list of the object and want to immediately unpack. `Dataclasses` don't support this out of the box.

**Comment by vapier** [comment]
it isn't whether every single use should be converted.  by your logic, none of the "considering-xxx" diagnostics should exist.  it's a question of whether most usage would be better off using dataclasses, and whether devs are aware of the newer style or continuing to write in the styles they have been for years.

**Comment by DanielNoord** [comment]
I think in general we try to have as little false positives as possible. Some of the `consider-xxx` messages already are too opinionated and have too many false positives. In this case I think we would face the same issue.
