### ISSUE TITLE
Discourage collections.namedtuple in favor of typing.NamedTuple

### ISSUE THREAD

**Issue by vapier** [pylint-dev/pylint#8660]
### Current problem

when using Python 3.8+, collections.namedtuple is archaic, and should be flagged for upgrading

### Desired solution

when collections.namedtuple is seen, recommend using typing.NamedTuple instead

**Comment by DanielNoord** [comment]
Don't we already do this?

**Comment by mbyrnepr2** [comment]
Thanks for the issue. I don’t think this is flagged currently and I don’t think it should be; [collections.namedtuple](https://docs.python.org/3/library/collections.html#collections.namedtuple) is still part of the language, right?

**Comment by jacobtylerwalls** [comment]
I think the word "deprecation" got us side-tracked; the request is more like, "add a new checker to suggest upgrading your namedtuples defined with collections.namedtuple to the [more elegant notation](https://docs.python.org/3.11/library/collections.html?highlight=elegant#collections.namedtuple) of typing.NamedTuple".

**Comment by jacobtylerwalls** [comment]
This would be a good candidate for the CodeStyleChecker extension.
