### ISSUE TITLE
Remove bad link from pylint.org front page

### ISSUE THREAD

**Issue by rothfralick** [pylint-dev/pylint#8703]
### Current problem

From pylint.org, a link that reads [Full list of codes (wiki)](https://pylint-messages.wikidot.com/) directs to pylint-messages.wikidot.com, which redirects to 99kz.cn, which is entirely in Chinese and not related to pylint.

### Desired solution

Use a better link.

**Comment by jacobtylerwalls** [comment]
Thanks, but unfortunately nobody here controls that domain. See investigation at https://github.com/pylint-dev/pylint/issues/7384#issuecomment-1370225190.
