### ISSUE TITLE
bad-plugin-value

### ISSUE THREAD

**Issue by deadex-ng** [pylint-dev/pylint#8705]
### Question

I have been working on a custom pylint plugin and would like to turn it into a python package. However, when I run pip install the package locally and run:
`pylint --load-plugins=pylint-no-blank-line  /home/fumba/Documents/test.py`

I get the following error:

`************* Module Command line or configuration file
Command line or configuration file:1:0: E0013: Plugin 'pylint-no-blank-line' is impossible to load, is it installed ? ('No module named 'pylint-no-blank-line'') (bad-plugin-value)
************* Module test
/home/fumba/Documents/test.py:1:0: C0114: Missing module docstring (missing-module-docstring)
/home/fumba/Documents/test.py:1:0: C0116: Missing function or method docstring (missing-function-docstring)
/home/fumba/Documents/test.py:11:3: E0602: Undefined variable 'some_var' (undefined-variable)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
` 
I thought this was issue with the way I set up my package so I tried using a different [package](https://github.com/m-burst/pylint-requests) and I was getting a similar error message. I successfully installed the package using pip but running:

`pylint --load-plugins=pylint-requests /workspaces/codespaces-blank/test.py` 

I also got a similar error:
`@deadex-ng ➜ /workspaces/codespaces-blank/files $ pylint --load-plugins=pylint-requests /workspaces/codespaces-blank/test.py
************* Module Command line or configuration file
Command line or configuration file:1:0: E0013: Plugin 'pylint-requests' is impossible to load, is it installed ? ('No module named 'pylint-requests'') (bad-plugin-value)
************* Module test
/workspaces/codespaces-blank/test.py:3:0: C0303: Trailing whitespace (trailing-whitespace)
/workspaces/codespaces-blank/test.py:4:0: C0304: Final newline missing (missing-final-newline)
/workspaces/codespaces-blank/test.py:1:0: C0114: Missing module docstring (missing-module-docstring)

Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)

@deadex-ng ➜ /workspaces/codespaces-blank/files $ 
`
Could you please help me with what is wrong here?

### Documentation for future user

Please provide more information on the error [here](https://pylint.readthedocs.io/en/latest/user_guide/messages/error/bad-plugin-value.html)

### Additional context

System Information:
    Operating system: Ubuntu 20.04.6 LTS (Focal Fossa)
    Python version: Python 3.10.4
    pylint version: pylint 2.17.3
    pylint-requests version: 0.1.1

**Comment by Pierre-Sassoulas** [comment]
You need to use the python namespace not the package name. (your_namespace.the_module not pip-package-name). See examples where pylint.extensions.checkers are used in our repo or elsewhere.
