### ISSUE TITLE
OptionValueError: option confidence: invalid value: 'CONTROL_FLOW', should be in ['HIGH', 'INFERENCE', 'INFERENCE_FAILURE', 'UNDEFINED']

### ISSUE THREAD

**Issue by knipknap** [pylint-dev/pylint#8709]
### Bug description

I can't get Pylint to start, running into the following traceback:

```
$ pylint --help
Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3/dist-packages/pylint/__init__.py", line 24, in run_pylint
    PylintRun(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/pylint/lint/run.py", line 348, in __init__
    linter.load_config_file()
  File "/usr/lib/python3/dist-packages/pylint/config/option_manager_mixin.py", line 340, in load_config_file
    self.global_set_option(option, value)
  File "/usr/lib/python3/dist-packages/pylint/config/option_manager_mixin.py", line 190, in global_set_option
    self._all_options[opt].set_option(opt, value)
  File "/usr/lib/python3/dist-packages/pylint/lint/pylinter.py", line 691, in set_option
    checkers.BaseTokenChecker.set_option(self, optname, value, action, optdict)
  File "/usr/lib/python3/dist-packages/pylint/config/options_provider_mixin.py", line 54, in set_option
    value = _validate(value, optdict, optname)
  File "/usr/lib/python3/dist-packages/pylint/config/option.py", line 139, in _validate
    return _call_validator(_type, optdict, name, value)
  File "/usr/lib/python3/dist-packages/pylint/config/option.py", line 120, in _call_validator
    return VALIDATORS[opttype](optdict, option, value)
  File "/usr/lib/python3/dist-packages/pylint/config/option.py", line 108, in <lambda>
    "multiple_choice": lambda opt, name, value: _multiple_choice_validator(
  File "/usr/lib/python3/dist-packages/pylint/config/option.py", line 72, in _multiple_choice_validator
    raise optparse.OptionValueError(msg % (name, csv_value, choices))
optparse.OptionValueError: option confidence: invalid value: 'CONTROL_FLOW', should be in ['HIGH', 'INFERENCE', 'INFERENCE_FAILURE', 'UNDEFINED']
```

`pylint --version` works however.

### Configuration

```ini
I didn't configure anything, just "apt install pylint".
```

### Command used

```shell
`pylint --help`

Or just `pylint file.py`
```

### Pylint output

```shell
See above.
```

### Expected behavior

Anything but a traceback.

### Pylint version

```shell
Version: 2.12.2-1 (from Ubuntu Jammy)

$ pylint --version
pylint 2.12.2
astroid 2.9.3
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
```

### OS / Environment

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

### Additional dependencies

aiohttp==3.8.4
aiosignal==1.3.1
alabaster==0.7.12
amqp==5.0.9
anyjson==0.3.3
appdirs==1.4.4
apturl==0.5.2
astroid==2.9.3
async-timeout==4.0.2
attrs==21.2.0
autobahn==21.11.1
Automat==20.2.0
Babel==2.8.0
base58==1.0.3
bcrypt==3.2.0
beautifulsoup4==4.10.0
beniget==0.4.1
bert-extractive-summarizer==0.10.1
bidict==0.22.1
billiard==3.6.4.0
bleach==4.1.0
blinker==1.4
blis==0.7.9
breadability==0.1.20
Brlapi==0.8.3
Brotli==1.0.9
cached-property==1.5.2
cachetools==5.0.0
catalogue==2.0.8
cbor==1.0.0
celery==5.2.3
certifi==2020.6.20
cffi==1.15.0
chardet==4.0.0
charset-normalizer==3.1.0
chrome-gnome-shell==0.0.0
click==8.1.3
click-didyoumean==0.0.3
click-plugins==1.1.1
click-repl==0.2.0
cmarkgfm==0.8.0
colorama==0.4.6
command-not-found==0.3
confection==0.0.4
constantly==15.1.0
cryptography==3.4.8
cssselect==1.1.0
cupshelpers==1.0
cycler==0.11.0
cymem==2.0.7
Cython==0.29.28
dbus-python==1.2.18
decorator==4.4.2
defer==1.0.6
demjson==2.2.4
distro==1.7.0
distro-info===1.1build1
dnspython==2.3.0
docker==5.0.3
docker-compose==1.29.2
dockerpty==0.4.1
docopt==0.6.2
docutils==0.17.1
duckduckgo-search==2.8.5
duplicity==0.8.21
dxf2gcode==20170925
ecdsa==0.18.0b1
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl
ephem==4.1.3
eventlet==0.33.3
fasteners==0.14.1
filelock==3.9.0
Flask==2.0.1
Flask-Cors==3.0.10
Flask-Login==0.5.0
Flask-SocketIO==5.3.2
flatbuffers===1.12.1-git20200711.33e2d80-dfsg1-0.6
fonttools==4.29.1
frozenlist==1.3.3
fs==2.4.12
future==0.18.2
gast==0.5.2
geomdl==5.3.1
gevent==22.10.2
gevent-websocket==0.10.1
gitdb==4.0.10
GitPython==3.1.30
google-api-python-client==1.7.11
google-auth==1.5.1
google-auth-httplib2==0.1.0
greenlet==2.0.2
gTTS==2.3.1
gunicorn==20.1.0
h11==0.14.0
hausdorff==0.2.6
html5lib==1.1
httplib2==0.20.2
huggingface-hub==0.12.0
hyperlink==21.0.0
idna==3.3
ifaddr==0.1.7
imagesize==1.3.0
img2pdf==0.4.2
importlib-metadata==4.6.4
incremental==21.3.0
iniconfig==1.1.1
isodate==0.6.1
isort==5.6.4
itsdangerous==2.1.0
JACK-Client==0.5.3
jeepney==0.7.1
Jinja2==3.0.3
joblib==1.2.0
jsonschema==3.2.0
kazam==1.4.5
keyring==23.5.0
kiwisolver==1.3.2
kombu==5.2.3
langcodes==3.3.0
language-selector==0.1
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
lazy-object-proxy==0.0.0
lexrank==0.1.0
lockfile==0.12.2
logilab-common==1.8.2
loguru==0.6.0
louis==3.20.0
lxml==4.8.0
lz4==3.1.3+dfsg
macaroonbakery==1.3.1
Markdown==3.4.1
MarkupSafe==2.0.1
matplotlib==3.5.1
mccabe==0.6.1
minio==7.1.13
mnemonic==0.19
monotonic==1.6
more-itertools==8.10.0
mpi4py==3.1.3
mpmath==0.0.0
msgpack==1.0.3
multidict==6.0.4
murmurhash==1.0.9
mypy-extensions==0.4.3
netifaces==0.11.0
nltk==3.8.1
numpy==1.21.5
numpy-stl==2.8.0
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
oauth2client==4.1.3
oauthlib==3.2.0
olefile==0.46
openai==0.27.2
orjson==3.8.9
packaging==21.3
PAM==0.4.2
paramiko==2.9.3
passlib==1.7.4
path==16.6.0
path.py==12.5.0
pathspec==0.9.0
pathy==0.10.1
pdfarranger==1.8.2
pexpect==4.8.0
pikepdf==5.0.1+dfsg
Pillow==9.0.1
pinecone-client==2.2.1
Pivy==0.6.5
pkginfo==1.8.2
platformdirs==2.6.2
playsound==1.2.2
pluggy==0.13.0
ply==3.11
preshed==3.0.8
prompt-toolkit==3.0.28
protobuf==3.12.4
ptyprocess==0.7.0
py==1.10.0
py-slvs==1.0.3
py-ubjson==0.16.1
pyalsaaudio==0.8.4
pyasn1==0.4.8
pyasn1-modules==0.2.1
pycairo==1.20.1
pycollada==0.6
pycountry==22.3.5
pycparser==2.21
pycryptodome==3.16.0
pycups==2.0.1
pydantic==1.10.4
PyDrive==1.3.1
Pygments==2.11.2
PyGObject==3.42.1
PyHamcrest==2.0.2
PyICU==2.8.1
pyinotify==0.9.6
PyJWT==2.3.0
pyliblo==0.10.0
pylint==2.12.2
pymacaroons==0.13.0
PyNaCl==1.5.0
PyOpenGL==3.1.5
pyOpenSSL==21.0.0
pyparsing==2.4.7
pypng==0.0.20
PyQRCode==1.2.1
PyQt5==5.15.6
PyQt5-sip==12.9.1
pyRFC3339==1.1
pyrsistent==0.18.1
pyserial==3.5
pytest==6.2.5
python-apt==2.4.0+ubuntu1
python-dateutil==2.8.1
python-debian===0.1.43ubuntu1
python-dotenv==1.0.0
python-engineio==4.3.4
python-memcached==1.58
python-snappy==0.5.3
python-socketio==5.7.2
python-utils==2.2.0
pythran==0.10.0
PyTrie==0.4.0
pytz==2022.1
pyxdg==0.27
PyYAML==6.0
rdflib==6.1.1
readability-lxml==0.8.1
readme-renderer==34.0
redis==4.4.2
regex==2022.10.31
reportlab==3.6.8
requests==2.28.2
requests-toolbelt==0.9.1
rfc3986==1.5.0
roman==3.3
rsa==4.8
scikit-learn==1.2.1
scipy==1.8.0
scour==0.38.2
SecretStorage==3.3.1
sentry-sdk==1.4.3
service-identity==18.1.0
Shapely==1.8.0
simplejson==3.17.6
six==1.16.0
smart-open==6.3.0
smmap==5.0.0
snowballstemmer==2.2.0
sortedcontainers==2.1.0
soupsieve==2.3.1
spacy==3.5.0
spacy-legacy==3.0.12
spacy-loggers==1.0.4
SPARQLWrapper==1.8.5
Sphinx==4.3.2
SQLAlchemy==1.4.31
srsly==2.4.5
stream-inflate==0.0.14
stream-unzip==0.0.78
sumy==0.11.0
sympy==1.9
systemd-python==234
texttable==1.6.4
thinc==8.1.7
threadpoolctl==3.1.0
tiktoken==0.3.3
tokenizers==0.13.2
toml==0.10.2
torch==1.13.1
tqdm==4.64.1
transformers==4.26.0
twine==3.8.0
Twisted==22.1.0
txaio==21.2.1
typer==0.7.0
typing_extensions==4.4.0
u-msgpack-python==2.3.0
ubuntu-advantage-tools==8001
ubuntu-drivers-common==0.0.0
ufoLib2==0.13.1
ufw==0.36.1
ujson==5.1.0
unattended-upgrades==0.1
unicodedata2==14.0.0
uritemplate==3.0.1
uritools==4.0.1
urlextract==1.8.0
urllib3==1.26.5
usb-creator==0.3.7
uvicorn==0.20.0
vine==5.0.0
wadllib==1.3.6
wasabi==1.1.1
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.2.3
Werkzeug==2.0.2
wrapt==1.13.3
wsaccel==0.6.3
xdg==5
xkit==0.0.0
yamllint==1.26.3
yarl==1.8.2
zeroconf==0.38.3
zipp==1.0.0
zope.event==4.6
zope.interface==5.5.2

**Comment by knipknap** [comment]
Nevermind: The cause is a .pylintrc that already existed in the repo I was working on, and that had the unsupported CONTROL_FLOW option. Deleting that option from the file fixes the issue.

**Comment by Pierre-Sassoulas** [comment]
Control flow is a new confidence level, probably not supported by pylint 2.12.2 which is a very old version of pylint. I would suggest getting pylint directly from pip and not from debian because debian repository are lagging.
