### ISSUE TITLE
Feature request: `generated-members` equivalent to suppress `no-name-in-module`

### ISSUE THREAD

**Issue by mcowpert** [pylint-dev/pylint#8729]
### Steps to reproduce

1. Define a module ('baz') using apipkg to specify the API
2. Write code with `from baz import some_api_name`
3. Lint

### Current behavior
Line is flagged with `no-name-in-module`

### Expected behavior
Desired: a configuration setting similar to `generated-members` specifying modules to suppress this error

### `python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"` output
If this matters: 2.11.7

**Comment by mcowpert** [comment]
A colleague pointed out the `ignored-modules` option that I had missed. This feature does achieve what I wanted; I'm not sure if the feature suppresses more than the messages that were a problem for me. I'll leave it up to devs to decide; I'm OK with closing this ticket.

**Comment by DanielNoord** [comment]
Seems like we can indeed close this! Nice to see you found what you were looking for!
