### ISSUE TITLE
Detect unused modules

### ISSUE THREAD

**Issue by antonag32** [pylint-dev/pylint#8730]
### Current problem

Modules (files) which are not used may exist inside big projects without developers knowing it. By not used I mean they are not imported anywhere in the project. This is similar to dead code, but a little bit different, since all dead code tools I researched work on code and not files.

### Desired solution

A message, perhaps something like `unused-module` (seems to have existed sometime in the codebase) which applies to modules which exist in the project that were never imported

**Comment by Pierre-Sassoulas** [comment]
I suppose we should not raise if there is a single module without unit tests ? I don't know how easy it is to detect a module / unit test pair that is not used anywhere else. (If we can't do that I'm not sure this check is going to be useful). Also how can we detect that something is an API that is used outside of the package ? Do we raise for the manager class that import things and is not used inside the package because it's an API ?

**Comment by antonag32** [comment]
Thanks for taking the time to share your ideas. 

I think anything related to tests should automatically be excluded from this check. Since this works with `Import`, `ImportFrom`, and `Module` it is  simple to get the filename involved (Module has it, and imports AFAIK most of the time have a  Module as a direct parent), then I guess its just a matter of excluding anything with `tests/` in its filename.

The point about something being an API is a good point, I guess that would require an option in the configuration file, or at the very least a pylint directive on the  public API files.

I am also not sure if pylint as of now is equipped to run functional tests that  require a whole test project structure? All I  see is tests per file, so that would require extra-work since this is by nature a message  that needs multiple test files. I think  this is also a problem  in vulture but since it is a dedicated  tool the hassle may be justified.

**Comment by Pierre-Sassoulas** [comment]
> I am also not sure if pylint as of now is equipped to run functional tests that require a whole test project structure? All I see is tests per file, so that would require extra-work since this is by nature a message that needs multiple test files. 

We have some test that import other files but you're right that only one file is analysed in this case. There's a migration to do from the "old functional tests". 

I see you closed the issue, I did not have strong opinion about it but it does seem a little out of scope for pylint or at least hard to do. It doesn't mean that if someone is really motivated to do this it could be done as a plugin ;)

**Comment by antonag32** [comment]
Yeah no worries, I felt like my issue was polluting the board haha. I agree that it feels out of scope, and I have done it already in a plugin hehe, since it is a little bit more specialized it seems to fit better as a plugin. Maybe someday it can be incorporated in something more fitting like vulture

**Comment by Pierre-Sassoulas** [comment]
If the plugin is open-source, here would be a good place to link it 😉
