### ISSUE TITLE
Add CITATION.cff

### ISSUE THREAD

**Issue by schackartk** [pylint-dev/pylint#8760]
### Current problem

I would like to cite pylint in a research article and it is unclear how pylint should be cited.

### Desired solution

I would like pylint to have a CITATION.cff file in the root of the repository.

[GitHub recommends](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files), and integrates support for, [CITATION.cff](https://citation-file-format.github.io/) files. Inclusion of this file would immediately have these benefits:

- Users will have the necessary metadata to properly cite pylint.
- GitHub can automatically generate both APA and BibTeX formatted citations. A "Cite this repository" option will automatically appear on the repo's sidebar when viewed on a desktop browser.
- Reference managers like Zotero will automatically detect the metadata so the user can save the citation to their library.

### Additional context

Examples of popular packages using this are [pandas](https://github.com/pandas-dev/pandas) and [tensorflow](https://github.com/tensorflow/tensorflow).

I would be happy to create an initial version of this and open a PR if there is interest in possibly merging it after refinement.

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue and for citing pylint in your research. Definitely interested by merging what you can suggest and I think that would be pretty cool to have.
