### ISSUE TITLE
Refactor `unneeded-not` checker

### ISSUE THREAD

**Issue by orSolocate** [pylint-dev/pylint#8789]
### Current problem

A small suggestion to improve readability of this checker, since it covers not only the `not` keyword but also the `!=` symbol.

Also in the description, it might not be perfectly clear what a `unneeded negation` is.

### Desired solution

New name suggestion (or similar): `redundant-negation`

The description can be extended to this:

`Used when a boolean expression contains an unneeded negation, e.g. when two negation operators cancel each other out.`

**Comment by gracejiang16** [comment]
Can I try this issue?

**Comment by DanielNoord** [comment]
Yes! Do you need any pointers to start working on it?

**Comment by orSolocate** [comment]
@gracejiang16  yeah you can. should be super simple to change. 

I am glad there is an agreement about the change itself

**Comment by orSolocate** [comment]
1. rename the checker name in its implementation file, under the `pylint/checkers` folder (should be able to find it using search).
2. modify the description.
3. find the test file, should be under `tests/functional/u/unnecessary/unnecessary_not.py`. modify its name, modify the test results, look at the guide (in pylint docs) of how to run functional tests with the option to autoupdate the text file. also verify the test covers enough cases.
4. add more examples to bad/good.py codes located here:
`doc/data/messages/u/unneeded-not`
5. you can write a townscrier release note (see how to do it in the docs)

**Comment by DanielNoord** [comment]
You will also need to use the "old name" system, which we use to deprecate old names and reuse new names without breaking people's setup. You can search for "missing-docstring" to see how this works.

**Comment by gracejiang16** [comment]
> You will also need to use the "old name" system, which we use to deprecate old names and reuse new names without breaking people's setup. You can search for "missing-docstring" to see how this works.

I've done everything up to the townscrier note. But I've tried reading through issue#1164, if that's what you mean, and I'm still having some trouble figuring out how to proceed. Do you have any tips or pointers? Thank you again.

**Comment by orSolocate** [comment]
@gracejiang16 - I am not familiar with Daniel's note but I think that its best if you submit a PR connected to this issue, this way we could see what you did and could have a look.

**Comment by Pierre-Sassoulas** [comment]
Do not hesitate to open a merge request even if something's is not working yet. Regarding old_names here's an example: https://github.com/pylint-dev/pylint/blob/f815e9f5fcdd5caffc04e335fc4590a65989ef21/pylint/checkers/strings.py#L662
