### ISSUE TITLE
[primer] Flaky results from inference differences

### ISSUE THREAD

**Issue by jacobtylerwalls** [pylint-dev/pylint#8790]
See https://github.com/pylint-dev/pylint/issues/8758#issuecomment-1602996137 for a recent example of subtle differences in messages comparing unequal and causing noisy, irrelevant primer output.

Messages like `invalid-name` and `deprecated-typing-alias` seem to be the worst offenders.

**Comment by jacobtylerwalls** [comment]
I'll reopen if I see this again.

**Comment by Pierre-Sassoulas** [comment]
I had a long term plan to make the primer prettier by showing only what really changed, but my work branch is basically impossible to rebase at this point. Should have concluded the MR when I had the chance. It's not super simple to do, you need to decide if a message is a new message or a modified message from information that is not very stable. Basically some fields are more important than others. Also the commit is not set for the primed repo, which make this a shaky ground to decide from the json we have. And there's of course a lot of markdown output fine tunning to do.

**Comment by jacobtylerwalls** [comment]
Still happening, not particularly subtle.

See recent runs like https://github.com/pylint-dev/pylint/pull/8824#issuecomment-1622335183, on a PR only touching pyreverse 😭 .

**Comment by jacobtylerwalls** [comment]
I have reason to believe #8872 made this significantly more deterministic. Will reopen if I see it again.
