### ISSUE TITLE
Extend broad-exception-raised and broad-exception-caught to `except*`

### ISSUE THREAD

**Issue by jacobtylerwalls** [pylint-dev/pylint#8827]
_Originally posted by @clavedeluna in https://github.com/pylint-dev/pylint/issues/7703#issuecomment-1303843158_

***
Expect these examples to raise the same message:

```python
try:
    1 / 0
except Exception:
    pass
```

************* Module a
a.py:3:7: W0718: Catching too general exception Exception (broad-exception-caught)

```python
try:
    1 / 0
except* Exception:
    pass
```

************* Module a
a.py:2:4: W0104: Statement seems to have no effect (pointless-statement)

**Comment by azinneck0485** [comment]
Can I work on this issue?

I've spent some time looking into the code and added a dummy `visit_trystar` method to the `ExceptionChecker` class in exceptions.py.  This dummy method prints the value of `node.handler` to the console, which correctly indicates the line in my test code where `except*` is.

Should the contents of this method be similar to `visit_try`?

**Comment by jacobtylerwalls** [comment]
Hi @azinneck0485 thanks for getting started! I haven't looked in detail, but yes, that seems like a wise plan of action.

**Comment by Pierre-Sassoulas** [comment]
You can try to call visit_try directly in visit_try_star, add some functional tests and see how it goes, sometime you get lucky.

**Comment by azinneck0485** [comment]
looks like that works, luckily, for broad-exception-caught, pending functional tests ... thanks so much for the tip!
