### ISSUE TITLE
Detect useless type conversions

### ISSUE THREAD

**Issue by EugeneZelenko** [pylint-dev/pylint#8863]
### Current problem

N/A

### Desired solution

It'll be great to add check that will detect useless type conversions like `float(1.0)`.

**Comment by mbyrnepr2** [comment]
Thanks for the issue. Similar to https://github.com/pylint-dev/pylint/issues/8693 and both could be part of the same checker for unnecessary calls. Perhaps we could transfer this info to that ticket to keep things in one place but I’ll wait for input from others.

**Comment by mbyrnepr2** [comment]
I've added a note to 8693 so will close this one!
