### ISSUE TITLE
Print statistics how many files were checked in verbose.

### ISSUE THREAD

**Issue by matejsp** [pylint-dev/pylint#8935]
### Current problem

I am trying to fine tune pylint and when dealing with excludes I see that sometimes too many files were excluded and would like to compare with number of files in a project.

### Desired solution

After pylint completed I would like to have printed something similar to black:
```
black .
2 files reformatted, 13493 files left unchanged.
```

```
pylint *.py **/*.py --verbose
...
13493 files checked.
```

**Comment by DanielNoord** [comment]
We already store this information in our `LinterStats` so should be trivial to add. Might even be nice to include statistics about how many files were excluded?

**Comment by meltemkenis** [comment]
Hello, I would like to work on this issue if it is possible.
