### ISSUE TITLE
[Proposal] check for newline at end of json-file saves

### ISSUE THREAD

**Issue by Pymann** [pylint-dev/pylint#8943]
### Current problem

At leasr for linux systems and github it is preferrable to have a newline at the end of each json. And Iam spending whole live adding those....

maybe have a pylint-issue for this.

### Desired solution

Add detection of json files save, without newline added at the end.

**Comment by Pierre-Sassoulas** [comment]
This is out of scope for pylint. But, you can use pre-commit + end-of-file and json check from pre-commit and/or prettier for that (do check our pre-commit configuration at the root of the repository for an example).
