### ISSUE TITLE
The code to delete an undefined variable with `del var` causes an undefined-variable error

### ISSUE THREAD

**Issue by HongchengFan** [pylint-dev/pylint#9026]
**Description**

When I use `del var` to delete an undefined variable accidentally, Pylint causes an undefined-variable error.

Here is a minimal code snippet to reproduce the crash:
```
del x
```

Print the code in the file.py and execute `pylint file.py -E`.

**The Actual Output**

```
************* Module file
file.py:1:4: E0602: Undefined variable 'x' (undefined-variable)
```

**The Expected Output**

Code execution won't be blocked.

**Your Environment**

- Pylint version used:2.17.5
- Pylint command-line flags: pylint file.py -E
- Python version used: 3.9.0
- Operating system and version: Ubuntu 20.04.6 LTS

**Comment by mbyrnepr2** [comment]
Hi @HongchengFan as-written, the example does have an undefined variable, so the Pylint message makes sense.
Can you elaborate on your use-case please?
Here is what I've tried:

example.py:
```python
ANSWER = 42
del ANSWER
```
pylint example.py -E
```python
```

**Comment by mbyrnepr2** [comment]
Thanks for contributing the issue 👍
