### ISSUE TITLE
[feature request] New warning: too many positional arguments

### ISSUE THREAD

**Issue by sabik** [pylint-dev/pylint#9099]
### Current problem

With R0913 too-many-arguments now including keyword arguments (#8667), the reasonable setting for `max-args` is now larger, since it's not really a problem to have a dozen keyword-only arguments.

However, having a dozen positional arguments remains a poor design.

### Desired solution

A new warning for too many positional arguments, with a separately configurable maximum. This would warn when there are more than a very small number of positional arguments (including positional-only arguments).

This would be in addition to the existing too-many-arguments warning.

### Additional context

This has been previously suggested in comments on #8667

**Comment by jacobtylerwalls** [comment]
+1

**Comment by mbyrnepr2** [comment]
As for specification would this proposed checker be for emitting a message where a function or class is called? (as opposed to `too-many-arguments` which is emitted for the function or class _definition_. It sounds similar to the existing https://github.com/pylint-dev/pylint/issues/385.

**Comment by jacobtylerwalls** [comment]
As I'm hearing the request, it's just on the definition (and that's what I would suggest, too).

**Comment by sabik** [comment]
Yeah, I intended this to be on the definition, just like the too-many-arguments warning (but excluding keyword-only arguments from the count and with a separate maximum)

**Comment by mbyrnepr2** [comment]
I think the idea behind `too-many-arguments` is that, regardless of the argument being positional or keyword or positional-only (etc.), the function is complex by having too many of them (subjective I know :D) and doing too many things. At definition time this is possible because we have all the information we need (the number of params).

Would the new checker raise for this situation (where the function call has explicitly passed the names of the parameters)?
```python
def tomato(one, two, three, four, five, six):
    ...

tomato(one=1, two=2, three=3, four=4, five=5, six=6)
```

Perhaps if it were to raise for positional-only, then raising at definition time is ok:
```python
def tomato(one, two, three, four, five, six, /):
    ...

tomato(1, 2, 3, 4, 5, 6)
```

**Comment by flying-sheep** [comment]
I think https://github.com/pylint-dev/pylint/issues/8667 was a mistake. “too many total arguments” could be a separate rule, but it’s much less useful than restricting the number of positional arguments.

**Comment by mbyrnepr2** [comment]
I'm happy that 8667 sparked the conversation and that ambiguity will be removed with the introduction of the new checker.
I still feel that the spirit of [too-many-arguments](https://pylint.pycqa.org/en/stable/user_guide/messages/refactor/too-many-arguments.html) was to draw attention to a function that accepts a large number of arguments (irrespective of type) and to consider a re-design/refactor.

**Comment by tometzky** [comment]
Unfortunately, IMHO, significantly limiting number of keyword-only arguments only encourages bad practices, like:

- using `**kwargs` or a dict argument and losing useful checks for typos in args, required args, arg type checking with mypy etc;
- replacing arguments with a `dataclasses.dataclass` or `typing.NamedTuple`, but then soon be forced to disable `too-many-instance-attributes`;
- over-engineering with some special classes like `SomeFunctionArgumentGenerator` - no way it is simpler and less error prone.

There are other checks in pylint that discourage too complicated code, like too-many-branches and too-many-locals etc. which should be enough.

With no obvious refactoring path for reasonable number of positional-only arguments, the change in #8667 made a useful check into a forced bunch of `pylint: disable` comments. Please revert #8667 until too-many-positional with a reasonable default is added (maybe 15, like too-many-locals).

**Comment by flying-sheep** [comment]
far too late to go with your suggestion of reverting this, but a new code for it has been reserved: https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/too-many-positional.html

you could either implement it here or switch to / add Ruff to your project
