### ISSUE TITLE
Create a ``.readthedocs.yaml`` for the readthedoc build so it does not break "soon"

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [pylint-dev/pylint#9117]
### Current problem

Configuration files will soon be required by readthedoc and will no longer be optional. 

### Desired solution

[Read our blog post to create one](https://blog.readthedocs.com/migrate-configuration-v2/) and ensure your project continues building successfully.

### Additional context

Seems like soon was in the past and the deadline was pushed a little, the blog post announced September 25, 2023.

**Comment by DanielNoord** [comment]
We already have this right?

**Comment by Pierre-Sassoulas** [comment]
Checked a second time and I did see a [.readthedocs.yaml](https://github.com/pylint-dev/pylint/blob/main/.readthedocs.yaml) this time. But we still have the warning message on the readthedoc build page.

**Comment by DanielNoord** [comment]
Can you link to the warning messages? I can't find them.

**Comment by Pierre-Sassoulas** [comment]
![readthedoc_error](https://github.com/pylint-dev/pylint/assets/5493666/547289ad-c32b-4382-b01e-07b7fcb1afa0)

https://readthedocs.org/projects/pylint/builds/22125846/

**Comment by DanielNoord** [comment]
Feels like a bug where they are displaying this warning on any validation error for the configuration file. Other jobs don't show this error and the configuration in that file is invalid. I'm closing this as it doesn't seem we need to take any action.

**Comment by Pierre-Sassoulas** [comment]
Thank you for investigating, and sorry for the noise!
