### ISSUE TITLE
Add optional check for CapWords naming style for classes

### ISSUE THREAD

**Issue by samreynoldsmath** [pylint-dev/pylint#9123]
### Current problem

[PEP8 states](https://peps.python.org/pep-0008/#class-names) that class names should usually follow the CapWords convention. For instance, a class should usually be named MyClass rather than my_class.

There does not seem to be an option for pylint to check if the names of classes conform to the CapWords convention. (If I am mistaken, please let me know!) 

### Desired solution

I would like to have the option for pylint to check that class names adhere to the CapWords convention, as described above.

### Additional context

PEP8 states that the CapWords naming style for classes can be replaced with the naming convention for functions "in cases where the interface is documented and used primarily as a callable." It should be up to the user to decide if the latter is appropriate for their project. 

Given that PEP8 recommends, but does not strictly enforce, the CapWords naming style for classes, it might make sense to have this check be disabled by default. The feature could be enabled by editing a configuration file, like .pylintrc, pyproject.toml, etc. 

This will save our team a lot of time checking the source code manually. Thanks for your help!

**Comment by Pierre-Sassoulas** [comment]
There's invalid-name, possibly with a custom regex but in your case CapWord seems to be PascalCase, the default. Could you check the online Doc and report back, please ?

**Comment by samreynoldsmath** [comment]
Thanks for getting back to me, Pierre. You are correct that the recommended behavior is indeed what I suggested above. I did not see this earlier because of poor configuration on my part. Sorry for wasting your time!

**Comment by Pierre-Sassoulas** [comment]
No problem, I'm closing then :)
