### ISSUE TITLE
Add disclaimer to doc template for informational messages clarifying they don't affect score/exit code by default

### ISSUE THREAD

**Issue by alfish2000** [pylint-dev/pylint#9171]
### Question

I'd like to treat messages like I0021 as warnings in my CI system so that the pylint_runner would return a non-zero exit code.
I have enabled useless-suppression in .pylintrc and on the console I get the I0021 message printed properly.
But the pylint_runner still returns 0 as exit code so that the CI job does not detect this as a warning/info/error.
Is there a way to let the pylint_runner return non-zero for e.g. enabled I0021 messages?
Thanks in advance for any help

### Documentation for future user

Could be added e.g. here : https://pylint.readthedocs.io/en/latest/user_guide/messages/information/useless-suppression.html#useless-suppression-i0021
Or more generic somewhere where the informational messages like I00xx are explained

**Comment by Pierre-Sassoulas** [comment]
That would be the [``--fail-on`` option](https://pylint.pycqa.org/en/latest/user_guide/configuration/all-options.html#fail-on), or #2293 for a more modular fix. Not sure if we should add a link to this option on all the informational message.

**Comment by alfish2000** [comment]
> That would be the [`--fail-on` option](https://pylint.pycqa.org/en/latest/user_guide/configuration/all-options.html#fail-on), or #2293 for a more modular fix. Not sure if we should add a link to this option on all the informational message.

Thanks for your quick answer and the hint to the --fail-on option.

**Comment by jacobtylerwalls** [comment]
I can see it being nice to adjust the message page template to add a disclaimer on all the Informational messages that they aren't included in the score by default (and thus won't cause a failure on CI).

**Comment by alfish2000** [comment]
> > That would be the [`--fail-on` option](https://pylint.pycqa.org/en/latest/user_guide/configuration/all-options.html#fail-on), or #2293 for a more modular fix. Not sure if we should add a link to this option on all the informational message.
> 
> Thanks for your quick answer and the hint to the --fail-on option.

I've tested with --fail-on and pylint then returns with exit code 1.
But the pylint_runner then still returns with exit code 0.
pylint_runner uses "sys.exit(run.linter.msg_status)"
I assume that pylint returns still 0 in its msg_status
Where does this problem then have to be fixed?
Is it a pylint problem? Should pylint set a msg_status != 0 so that pylint_runner would also return with exit code != 0?
I have to debugged anything.
I just had a quick look at the pylint_runner code.
So this is just my assumption for the moment.

**Comment by jacobtylerwalls** [comment]
`pylint-runner` is maintained by [someone else](https://github.com/MasterOdin/pylint_runner). I'm not sure what the use case is for it.

**Comment by Pierre-Sassoulas** [comment]
I think the use case for pylint runner does not exists anymore now that the `--recursive` option was implemented in pylint.

**Comment by alfish2000** [comment]
> I think the use case for pylint runner does not exists anymore now that the `--recursive` option was implemented in pylint.

Thanks for pointing me to the --recursive option.

It seems to work so far.
Is there a way to print which files were processed by pylint?
For example with `pylint --recursive=y --reports=y .` I can see that 53 files are processed but 55 ".py" files are in my directory structure.
So how could I find out which 2 files were not processed?

**Comment by Pierre-Sassoulas** [comment]
I'm not sure such an option exists, did you try ``--verbose`` / ``-v`` ? Next option would be to add a logging [here](https://github.com/pylint-dev/pylint/blob/3de196c91bcf67e92e5413dea09eb65c4d15c37e/pylint/lint/pylinter.py#L662) manually:

**Comment by alfish2000** [comment]
> I'm not sure such an option exists, did you try `--verbose` / `-v` ? Next option would be to add a logging [here](https://github.com/pylint-dev/pylint/blob/3de196c91bcf67e92e5413dea09eb65c4d15c37e/pylint/lint/pylinter.py#L662) manually:

--verbose did not help

Adding `print(self.current_file)` [here](https://github.com/pylint-dev/pylint/blob/v3.0.2/pylint/lint/pylinter.py#L786) logged all the files.
Thanks for the hint.
