### ISSUE TITLE
pylintrc file license

### ISSUE THREAD

**Issue by Burton2000** [pylint-dev/pylint#9186]
### Question

Hi there,

We have a project that is Apache 2.0 and would like to include a pylintrc file inside our repository that we have generated from the command line and modified slightly.

The generated pylintrc file does not have a license on it but Pylint is licensed under GPLv2.0. Does this also mean that the generated pylintrc file should be GPLv2.0 license or do you explicitly say somewhere that this file is license free and we can attached an Apache 2.0 license to our generated pylintrc file?

Many thanks,
Richard

### Documentation for future user

License file

**Comment by DanielNoord** [comment]
Feel free to attach the license to your generated file. The code generating the file is licensed under GPL, but its output isn't. If that were the case all output of `pylint` would fall under that license.

Thanks for asking though!
