### ISSUE TITLE
Python 3.10 Match Case feature

### ISSUE THREAD

**Issue by curiousQuartz** [pylint-dev/pylint#9285]
### Current problem

I don't see this anywhere yet so I am opening this issue. 

https://docs.python.org/3/whatsnew/3.10.html#pep-634-structural-pattern-matching

Python 3.10.0 introduced structural pattern matching similar to the switch case statements in other languages. I have this in a my python file and am unable to run the pylint command since this feature is not recognized by pylint. 

The error I get is 
> E0001: Parsing failed: 'invalid syntax (<unknown>, line 249)' (syntax-error)

Even if other problems are in the code, this is the only error which appears.

### Desired solution

 Please add support for match-case statements introduced in python 3.10.0

### Additional context

 https://docs.python.org/3/whatsnew/3.10.html#pep-634-structural-pattern-matching

**Comment by Pierre-Sassoulas** [comment]
Are you launching pylint with a python interpreter that can parse match statement (>= 3.10) ? We rely on the python interpreter's ast to parse the code, so pylint launched on 3.9 will never be able to do this.

**Comment by jacobtylerwalls** [comment]
Feel free to reopen if you can present a case that fails with SyntaxError when running pylint on python 3.10+.
