### ISSUE TITLE
`--ignore-patterns` not working in primer config

### ISSUE THREAD

**Issue by jacobtylerwalls** [pylint-dev/pylint#9328]
This --ignore-patterns is not working:
https://github.com/pylint-dev/pylint/blob/420f2ae8d46a6ea90f39d9b3c59869f3200571a8/tests/primer/packages_to_prime.json#L38

Evidence:
https://github.com/pylint-dev/pylint/pull/9281#issuecomment-1839563461

**Comment by DanielNoord** [comment]
I'm probably over looking something simple, but which lines shows this isn't working?

**Comment by jacobtylerwalls** [comment]
Effect on [pandas](https://github.com/pandas-dev/pandas):
The following messages are now emitted:

Details
fixme-in-docstring:
TODO
https://github.com/pandas-dev/pandas/blob/3934e56f5d402f1ebf28ff89db02ce718e30cc8e/pandas/tests/indexing/test_partial.py#L1

**Comment by jacobtylerwalls** [comment]
I think maybe the leading (escaped) quote needs to go.

**Comment by DanielNoord** [comment]
Isn't is a regex? Seems like we're missing an `*`.

**Comment by jacobtylerwalls** [comment]
No longer important after we started priming only pandas core
