### ISSUE TITLE
feature request(plugins): option for loading all built-in optional extensions

### ISSUE THREAD

**Issue by Kristinita** [pylint-dev/pylint#9358]
### 1. Summary

It would be nice to have an option for loading all optional extensions, documented on the [**“Optional checkers” page**](https://pylint.pycqa.org/en/latest/user_guide/checkers/extensions.html), as in my example below.

If users can already get the desired behavior, please add to the documentation what they need to be done.

### 2. Example of desired behavior

```toml
# pylintrc.toml

# [INFO] Configuration if user wants to use all built-in optional checkers except “pylint.extensions.empty_comment”

[tool.pylint.main]

# [INFO] Load all optional checkers described in the Pylint documentation:
# https://pylint.pycqa.org/en/latest/user_guide/checkers/extensions.html
load-all-default-plugins = true

# [INFO] “ignored-default-plugins” applies if “load-all-default-plugins = true”
ignored-default-plugins = "pylint.extensions.empty_comment"
```

### 3. Reason why the feature is needed

The [**Pylint documentation describes**](https://pylint.pycqa.org/en/latest/user_guide/checkers/extensions.html#optional-checkers) solely a method where users can add optional plugins one by one.

```toml
# pylintrc.toml

[tool.pylint.main]

load-plugins = """
pylint.extensions.bad_builtin,
pylint.extensions.broad_try_clause,
pylint.extensions.check_elif,
pylint.extensions.code_style,
and so on
"""
```

The problem with this approach is that the following changes can occur in Pylint over time:

1. New plugins may appear
1. Some plugins may be deprecated
1. Plugins names may change

Pylint users do not keep up with Pylint changes all the time, and after a while they may not have new optional plugins in their configuration, but have deprecated plugins and plugins with incorrect names. But if Pylint will have the option like `load-all-default-plugins` from my example, users will always have all currently available built-in optional plugins with the correct names loaded.

### 4. Not helped

I haven’t been able to find how I can get the desired behavior using a search in:

1. Pylint documentation
1. Sections of the [**`pylintrc` example on this repository**](https://github.com/pylint-dev/pylint/blob/main/pylintrc)
1. This issue tracker
1. Google

Thanks.

**Comment by Pierre-Sassoulas** [comment]
This exists since pylint 2.12 as ``--enable-all-extensions ``. The documentation is lacking though, only the changelog from 2.12 talks about it.

**Comment by Kristinita** [comment]
**Type: Question** :question:

@Pierre-Sassoulas, excuse me, I can’t find, what should a user using the `--enable-all-extensions` option do to ignore some optional extensions? For example, as in the example from my issue if user wants to use all built-in optional checkers except `pylint.extensions.empty_comment`.

Thanks.

**Comment by Kristinita** [comment]
>  Excuse me, I can’t find: what should a user using the `--enable-all-extensions` option do to ignore some optional extensions? For example, as in the example from my issue if user wants to use all built-in optional checkers except `pylint.extensions.empty_comment`.

**Status: Fixed** :heavy_check_mark:

`--enable-all-extensions` [**must be command-line option**](https://github.com/pylint-dev/pylint/issues/8217), not an option in the configuration file.

```sh
# CLI command

pylint --rcfile pylintrc.toml --enable-all-extensions .
```

```toml
# pylintrc.toml

[tool.pylint."messages control"]

disable = "empty-comment"
```

Thanks.

**Comment by jacobtylerwalls** [comment]
Thanks for this issue. I agree that this limitation of `--enable-all-extensions` is worth addressing, and is tracked in #8217.
