### ISSUE TITLE
Different scores depending on invocation

### ISSUE THREAD

**Issue by Argon-** [pylint-dev/pylint#9364]
### Question

Greetings,
in an isolated environment (CI pipeline), two different ways to invoke pylint result in different scores although all else is equal. Same environment, same package versions (pylint 3.0.3), same OS and python, same pylintrc, same code to be linted. Yet,
`pylint my_repo --persistent=false --reports=n --score=y --jobs=1`
results in a different score than

```
    json_output = StringIO()
    reporter = pylint.reporters.json_reporter.JSON2Reporter(json_output)
    pylint.lint.Run(
        [
            f"my_repo",
            "--jobs=1",
            "--persistent=false",
            "--reports=n",
            "--score=y"
        ],
        reporter=reporter,
        exit=False)
    result = reporter.serialize_stats()
    pylint_score = result['score']
```

The latter is lower. I use a custom pylintrc that I verified both commands read (by changing the score formula). Explicitly specifying the rcfile with `--rcfile` yields the same results.
I could replicate this on a different server (fresh install). However, my local machine gets the same score for both invocations. All machines are running Debian. The order of the invocation does not matter.

My assumption is that these invocations have different default settings for certain parameters, but I cannot find anything about that in the documentation. Any ideas?

### Documentation for future user

Would be awesome to have documentation on how to run pylint from Python and get the same results and pitfalls.

**Comment by jacobtylerwalls** [comment]
#8217 comes to mind. But if it's not that, we'll need more concrete info to reproduce. Thanks.
