### ISSUE TITLE
[feature] Add a design check for unused self in class methods

### ISSUE THREAD

**Issue by qequ** [pylint-dev/pylint#9367]
### Current problem

when having a class like

```python
class MyClass:
    def my_method(self):
        return

```

that doesn't use self argument it would be great to add a misdesign check in pylint to sugest making it a static method

### Desired solution

running pylint on that code snippet 

```
pylint snippet.py
```

should alert that the method could be a static method

```
snippet.py ... method could a  be static method
```

**Comment by DanielNoord** [comment]
Aren't you describing no self use: https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/no-self-use.html#
