### ISSUE TITLE
logging-not-lazy tests appear to be incorrect

### ISSUE THREAD

**Issue by clavedeluna** [pylint-dev/pylint#9380]
### Bug description

These two lines  in functional tests for logging-not-lazy:
```python
logging.warn("%s, %s" % (4, 5))
logging.log(logging.INFO, "msg: %s" % "Run!")
```

indicate that this message will not be logged for them, but they're clearly lazy logging.

https://github.com/pylint-dev/pylint/blob/81bd39a575bbce3ab83e71d998eda5cce65a6c87/tests/functional/l/logging/logging_not_lazy.py#L21:L22

### Command used

```shell
pylint test.py
```

### Pylint output

```python
test.py:3:0: W1201: Use lazy % formatting in logging functions (logging-not-lazy)
test.py:3:0: W4902: Using deprecated method warn() (deprecated-method)
test.py:4:0: W1201: Use lazy % formatting in logging functions (logging-not-lazy)
```

### Expected behavior

I expect tests to indicate this behavior.

### Pylint version

```shell
pylint 3.0.0
astroid 3.0.0
Python 3.11.0 (main, Oct 25 2022, 14:13:24) [Clang 14.0.0 (clang-1400.0.29.202)]
```

**Comment by crazybolillo** [comment]
Should this apply? I was checking it but confusingly enough, `logging` actually points to `os`.

**Comment by Pierre-Sassoulas** [comment]
Ha, thank you @crazybolillo, the test are designed to be tricky logging is actually ``renamed_logging``.
