### ISSUE TITLE
Add a warning suggesting @staticmethod

### ISSUE THREAD

**Issue by dgutson** [pylint-dev/pylint#9390]
### Current problem

I propose that pylint suggests when a method could be declared as `@staticmethod` 

### Desired solution

Check if `self` is used in the body of the method

**Comment by dgutson** [comment]
@qequ

**Comment by Pierre-Sassoulas** [comment]
This seem to be ``no-self-use``: https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/no-self-use.html
