### ISSUE TITLE
Add a hint at " return'string' " or " while'string' "

### ISSUE THREAD

**Issue by chhongzh** [pylint-dev/pylint#9392]
### Current problem

```python
while"string":
    ...

def func():
    return"string"

# Yes, the above code can be run.
```

Use pylint to check the above code, and no prompt will occur.

(Output, Ignore module docstring)
```shell
$ pylint test.py --disable=C0114
************* Module test
--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 0.00/10, +10.00)

```

### Desired solution

So, is it possible to add a hint such as **"add spaces"** to the above code?

**Comment by Pierre-Sassoulas** [comment]
We had a message for that at some point but it was removed in 2.6.0. An auto-formatter will make this check useless and will fix it for you automatically. You can use [black ](https://github.com/psf/black) for that see #3572 (or [ruff fmt ](https://docs.astral.sh/ruff/formatter/) now that we're 4 years in the future).
