### ISSUE TITLE
Suggestion conflicting with black 2024 style for inlined semantic / empty classes

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [pylint-dev/pylint#9398]
### Bug description

```python
class DebugTrueDetected(Exception): ...
```

### Command used

```shell
pylint a.py
```

### Pylint output

```python
C0321: More than one statement on a single line (multiple-statements)
```

### Expected behavior

No conflict with black I guess ?

### Pylint version

```shell
pylint 3.0.3
```

**Comment by jacobtylerwalls** [comment]
Figure we should exempt Ellipsis and Pass from the calculation.

**Comment by mbyrnepr2** [comment]
`black` moves `pass` to the next line in this example, so might want to focus on `...` only?
```python
class Apple: pass
```

**Comment by jacobtylerwalls** [comment]
Either way, but I don't think it hurts to exempt pass from the pylint check. I'm surprised black treats them differently.

**Comment by Pierre-Sassoulas** [comment]
Agree with @jacobtylerwalls, let's make pylint consistent for those not using black.

**Comment by Pierre-Sassoulas** [comment]
After looking into it, a good half of our examples and functional tests are just something with ``pass`` at the end. We might want to add an option to permit to still raise for ``pass`` or ``...`` ?

**Comment by jacobtylerwalls** [comment]
Are we sure that's not just a shortcut taken by test authors? Is there any original discussion about the check?

**Comment by Pierre-Sassoulas** [comment]
So it seems it's a decision that was done a long time ago but not in Logilab so we have a little context, I've done a ~little~ lot of digging and the functional test come from 0781e73e19b4762aaea5a02726431584eef30a8e and the original file was renamed here ee2571c7f58023fbdab2079b33157b8d03646f7b, then #3224 happened, and was moved previously here 33b8185a, #2236 happened, moved in 26eb7f9a2e6cc6c229c6a86b6c6bb823e8f5de57 and in 170b3056db8c8057bd56b4fbcbbc1b510e035963 .  Then the history of the antique ``test/test_format.py`` point to f1209f53bb96cf4ef07f6d8f7c2f85699eba0b3c. Maybe there's more info on bitbucket (can't find the repo though) but it seems Jacob's hypothesis is likely.
