### ISSUE TITLE
Pylint 3.1.0 reports ByteString as deprecated class when  ``py-version =  3.8``

### ISSUE THREAD

**Issue by Wayonb** [pylint-dev/pylint#9489]
### Bug description

```python
ByteString class is deprecated in Python 3.9.
https://docs.python.org/3/library/typing.html#typing.ByteString

Since upgrading to Pylint 3.1, getting deprecated class warning even though the minimum py-version = 3.8
```

### Configuration

```ini
[MAIN]

# Minimum supported python version
py-version = 3.8
```

### Command used

```shell
14:18:25  + xargs python3 -m pylint --rcfile C:/Users/Administrator/jenkins/workspace/linters/python/.pylintrc --disable=duplicate-code
```

### Pylint output

```python
14:19:12  ************* Module symbolchain.nc
14:19:12  symbolchain\nc\__init__.py:13:0: W4904: Using deprecated class ByteString of module typing (deprecated-class)
14:19:12  ************* Module symbolchain.sc
14:19:12  symbolchain\sc\__init__.py:13:0: W4904: Using deprecated class ByteString of module typing (deprecated-class)
```

### Expected behavior

Pylint not to report the warning.

### Pylint version

```shell
pylint 3.1
Python 3.12
```

**Comment by Pierre-Sassoulas** [comment]
I think this is voluntary afair. Python itself is going to warn you in python 3.9 or above, what would be the value added by this check if it only warned when python already does ? (Can't search for the original discussion easily as I'm on mobile).

**Comment by jacobtylerwalls** [comment]
Right, even if your lowest supported version is 3.8, it's still something that needs to be removed.

**Comment by jacobtylerwalls** [comment]
Decision to not use `py-version` for deprecated checkers discussed in https://github.com/pylint-dev/pylint/pull/5876#issuecomment-1062541176
