### ISSUE TITLE
Pylint gets stuck on syntax errors, any way to get the whole report even if there is syntax errors?

### ISSUE THREAD

**Issue by Alif829** [pylint-dev/pylint#9588]
### Question

 is there a way to get the whole issues of the code even with syntax errors? because currently, pylint gets stuck if it gets syntax error and flag only that syntax error issue not other issues even if they are available.

### Documentation for future user

I expected this information to be in the configuration

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue, could you review #9589 please ? :)
