### ISSUE TITLE
Which Messages output more than one line?

### ISSUE THREAD

**Issue by carlescufi** [pylint-dev/pylint#9612]
### Question

I would like to know the exact output format of different Messages, for machine-parsing. In particular it would be great if the documentation stated the output format for each message in a way that includes this information.

### Documentation for future user

Let's take an example:
https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/duplicate-code.html

The output specified for that Message is:
`Similar lines in %s files %s`

but it turns out that the second `%s` actually dumps a bunch of lines with the duplicate code apparently, which is not obvious from the output specification.

I would like to see documented that certain Messages output more than just a single line.

**Comment by Pierre-Sassoulas** [comment]
Did you try using a machine output reporter directly ? The Json reporter for example.

**Comment by carlescufi** [comment]
> Did you try using a machine output reporter directly ? The Json reporter for example.

I did not, no. Perhaps this would be the better way of handling this then. I wasn't aware of the option.
