### ISSUE TITLE
[Feature] new lint rule to require a comment #. (or #/, new line) at end each python block.

### ISSUE THREAD

**Issue by EdSaleh** [pylint-dev/pylint#9685]
### Current problem

[Feature] new lint rule to require a comment #. at end each python block.

### Desired solution

Create a new rule to require that each block must end with # or #. (other options: #\, a new line, selected by developer)
This would work as a curly braces blocks found in C style languages.
Also, this could also be used to reformat python code by code editor to fix any indentation issues.

Users can also use a different word symbol or use a new line for this purpose. (#., #/, newline, etc). The user the option to select the keyword they would like to have for the project.

Example:

```python
import string
def atbash(sequence: str) -> str:
    """
    Example
    """
    output = ""
    for i in sequence:
        extract = ord(i)
        if 65 <= extract <= 90:
            output += chr(155 - extract)
        #.
        elif 97 <= extract <= 122:
            output += chr(219 - extract)
        #.
        else:
            output += i
        #.
    #.
    return output
#.
```

**Comment by Pierre-Sassoulas** [comment]
Please don't reopen closed issues.

**Comment by EdSaleh** [comment]
> Please don't reopen closed issues.

I added new info to the topic. I will be looking into creating a plugin as suggested for this feature.

**Comment by EdSaleh** [comment]
@Pierre-Sassoulas 
I have also contributed to rust lint previously and my proposal was completed and merged.
https://github.com/rust-lang/rust-clippy/issues/2685

**Comment by DanielNoord** [comment]
You did not contribute, it was written by somebody else, and the largest discussion in that PR was about how to correctly phrase why it was such a bad lint (https://github.com/rust-lang/rust-clippy/pull/3494/).

I also see you link to that issue in various other repositories (https://github.com/modularml/mojo/issues/2929 and https://github.com/astral-sh/ruff/issues/11698) where you have received similar negative responses. To keep all open source maintainers from going insane and spending too much time on your unnecessary issues and comments consider this your last warning before I ban you from this organisation and ban you for spamming various repositories.

Read up on tools your opening issues against, see what they design philosophy is and act like the maintainers ask you to.

Good luck with writing your plugin! I hope to see it on PyPI one day 😄

**Comment by EdSaleh** [comment]
> You did not contribute, it was written by somebody else, and the largest discussion in that PR was about how to correctly phrase why it was such a bad lint ([rust-lang/rust-clippy#3494](https://github.com/rust-lang/rust-clippy/pull/3494)).
> 
> I also see you link to that issue in various other repositories ([modularml/mojo#2929](https://github.com/modularml/mojo/issues/2929) and [astral-sh/ruff#11698](https://github.com/astral-sh/ruff/issues/11698)) where you have received similar negative responses. To keep all open source maintainers from going insane and spending too much time on your unnecessary issues and comments consider this your last warning before I ban you from this organisation and report you for spamming various repositories.
> 
> Read up on tools your opening issues against, see what they design philosophy is and act like the maintainers ask you to.
> 
> Good luck with writing your plugin! I hope to see it on PyPI one day 😄

My proposal is the older and first one, and it's marked completed and merged as stated on the issue. I didn't code it though. Let's continue with pylint here. As I said, I am looking into implementing for this feature.

**Comment by EdSaleh** [comment]
> You did not contribute, it was written by somebody else, and the largest discussion in that PR was about how to correctly phrase why it was such a bad lint ([rust-lang/rust-clippy#3494](https://github.com/rust-lang/rust-clippy/pull/3494)).
> 
> I also see you link to that issue in various other repositories ([modularml/mojo#2929](https://github.com/modularml/mojo/issues/2929) and [astral-sh/ruff#11698](https://github.com/astral-sh/ruff/issues/11698)) where you have received similar negative responses. To keep all open source maintainers from going insane and spending too much time on your unnecessary issues and comments consider this your last warning before I ban you from this organisation and report you for spamming various repositories.
> 
> Read up on tools your opening issues against, see what they design philosophy is and act like the maintainers ask you to.
> 
> Good luck with writing your plugin! I hope to see it on PyPI one day 😄

I'm not sure why would you deal funnily or sarcastically with this proposal. This is not a good environmental for proposals or new ideas. I just proposed an idea that I think could be helpful for some people, particularly people coming for C style languages, while following python syntax and conventions. Finally it's your decision at the end whether to accept it or not for this proposal.
