### ISSUE TITLE
[Feature] new lint rule to require "new line" at end each code block.

### ISSUE THREAD

**Issue by EdSaleh** [pylint-dev/pylint#9691]
### Current problem

Hello,

It's always recommend practice style to add a new line at the end of each code block. Please create a lint rule to enforce this practice and in addition, allowing different forms of newline/comment (#., #) form for this purpose would be helpful for user.
This is just a proposal and an improvement to plugin, and your opinion is respected as the plugin developer.

Thank you

### Desired solution

[Feature] new lint rule to require "new line" at end each python block.

### Additional context

[Feature] new lint rule to require "new line" at end each python block.

**Comment by Pierre-Sassoulas** [comment]
Please do not re-open closed issue. You already did in https://github.com/pylint-dev/pylint/issues/9685 and I already asked to not do that. We already discussed this feature proposal in https://github.com/pylint-dev/pylint/issues/9684 and two maintainers clearly said this was not going to be included in pylint and proposed a way forward if you want to create a plugin. This is your final warning before you get blocked from the whole organization.
