### ISSUE TITLE
Feature Request: Have multiple types for a naming-style

### ISSUE THREAD

**Issue by JupperTV** [pylint-dev/pylint#9735]
### Current problem
I like the idea of the pre-defined styles. What really surprised me, is that you couldn't add multiple styles to a naming-style.

This happened when I set `variable-naming-style` to `camelCase, PascalCase` in my .pylintrc and ran pylint:

```
D:\>pylint main.py
usage: pylint [options]
pylint: error: argument --variable-naming-style: invalid choice: 'camelCase, PascalCase' (choose from 'snake_case', 'camelCase', 'PascalCase', 'UPPER_CASE', 'any')
```

### Desired solution

I would like pylint to consider multiple naming conventions for a naming-style. A setup like this:

.pylintrc:
```config
...
const-naming-style=camelCase, PascalCase, UPPER_CASE
# or 
const-naming-style=camelCase,
                   PascalCase,
                   UPPER_CASE
...
```

main.py:
```py
"""Example Script"""

thisIsFine = 5
ThisIsAlsoFine = "..."
this_is_not_fine = True
```

*Could* output something like this:
```
D:\>pylint main.py
************* Module main
D:\main.py:5:0: C0103: Constant name "this_is_not_fine" doesn't conform to camelCase, PascalCase, or UPPER_CASE naming style (invalid-name)

------------------------------------------------------------------
Your code has been rated at 6.67/10 (previous run: 3.33/10, +3.33)
```

### Additional context

Btw. #1013 is about adding the pre-defined styles. This is about being able to set multiple conventions to a naming-style.

**Comment by DanielNoord** [comment]
I agree. If you really want this I'd say you can create something with the `rgx` version of the option and try to combine both regular expressions.

You can find the regular expressions we use internally for both styles in our codebase.
