### ISSUE TITLE
remap FIXMEs as INFO 

### ISSUE THREAD

**Issue by tbutler-qontigo** [pylint-dev/pylint#9761]
### Question

Hi
We used to use pylint 2 with `pylint-fixme-info` to downgrade FIXME, TODO etc to INFO level but that no longer works with pylint 3.
Is there a way to do it "natively"?

We don't need any fancy remapping of specific issues - just a basic "treat them all as INFO"

thanks

### Documentation for future user

If it is possible, I would expect it to be documented where the `.pylintrc` options are documented for FIXME treatment

**Comment by DanielNoord** [comment]
Sadly there isn't. Please check out https://github.com/pylint-dev/pylint/issues/2293 for updates.
