### ISSUE TITLE
Add check for using major 3.11 and 3.12 features with lower `--py-version`

### ISSUE THREAD

**Issue by jacobtylerwalls** [pylint-dev/pylint#9791]
### Current problem

Add `using-exception-group-in-unsupported-version` and
`using-generic-type-syntax-in-unsupported-version` for uses of Python 3.11+ or
3.12+ features on lower supported versions provided with `--py-version`.

### Desired solution

new msgs

**Comment by jolaf** [comment]
It's not working for me on `pylint` 3.3.1:

```
pylintrc:1: [W0012(unknown-option-value), ] Unknown option value for '--enable', expected a valid pylint message and got 'using-exception-group-in-unsupported-version'
```

**Comment by Pierre-Sassoulas** [comment]
What's your output for ``pylint --version`` @jolaf ?

**Comment by jacobtylerwalls** [comment]
Ah, it's _groups_, not group.

**Comment by jacobtylerwalls** [comment]
I updated the github release markdown, will PR a release note fix shortly. 👍
