### ISSUE TITLE
Clarify `no-else-raise` and `no-else-return` also apply to try/except

### ISSUE THREAD

**Issue by jolaf** [pylint-dev/pylint#9901]
### Bug description

```python
def f() -> None:
    try:
        assert False
    except Exception:  # pylint: disable=try-except-raise
        raise
    else:
        pass

    try:
        assert False
    except Exception:
        return
    else:
        pass
```

### Command used

```shell
pylint test.py
```

### Pylint output

```python
************* Module test
test.py:2: [R1720(no-else-raise), f] Unnecessary "else" after "raise", remove the "else" and de-indent the code inside it
test.py:9: [R1705(no-else-return), f] Unnecessary "else" after "return", remove the "else" and de-indent the code inside it
```

### Expected behavior

No error reports.

As far as I understand, `no-else-raise`/`no-else-return` are supposed to be produced for `if`-`else` operators.

But in this example `else` is part of `try`-`except`-`else` operators, and the errors are completely inappropriate.

### Pylint version

```shell
pylint 3.2.6
astroid 3.2.4
Python 3.12.3 (main, Jul 31 2024, 17:43:48) [GCC 13.2.0]
```

### OS / Environment

Ubuntu 24.04.1

**Comment by jacobtylerwalls** [comment]
These aren't errors, they're refactoring messages. They still apply here, but we should update the documentation to clarify, since the documentation only mentions if/else.
