### ISSUE TITLE
FAQ: it *is* possible to run pylint automatically

### ISSUE THREAD

**Issue by edreamleo** [pylint-dev/pylint#9959]
### Bug description

[This](https://pylint.readthedocs.io/en/latest/faq.html#i-want-to-use-pylint-on-each-keystroke-in-my-ide-how-can-i-do-that) section of the FAQ is misleading.

Sure, running pylint on each keystroke is out of the question. But [this Leo PR](https://github.com/leo-editor/leo-editor/pull/4068) demonstrates that IDE's can lint files (in the background!) when Leo writes a changed file.

### IDE code to run pylint in the background when saving changed files

```python
# This is all Leo (IDE) code. There is no great need to understand it.

def run_pylint(self, fn: str, p: Position) -> None:
    """Run pylint on fn with the given pylint configuration file."""
    c, rc_fn = self.c, self.rc_fn

    # Invoke pylint directly.
    is_win = sys.platform.startswith('win')
    args = ','.join([f"'--rcfile={rc_fn}'", f"'{fn}'"])
    if is_win:
        args = args.replace('\\', '\\\\')
    command = (
        f'{sys.executable} -c "from pylint import lint; args=[{args}]; lint.Run(args)"')
    if not is_win:
        command = shlex.split(command)  # type:ignore
    
    # Run the command using the BPM.
    bpm = g.app.backgroundProcessManager
    bpm.start_process(c, command, fn=fn, kind='pylint')
```

### Pylint output

Leo outputs pylint messages in Leo's log pane.
The user can click on the links to go to the correct Leo (outline) node.

### Expected behavior

Revise these words in the FAQ:

I want to use pylint on each keystroke in my IDE, how can I do that ?

Don't do it: pylint's full suite of checks is not fast enough for that and never will be. pylint is best suited for linting on save for small projects, or for a continuous integration job or a git pre-push hook for big projects. The larger your repository is, the slower pylint will be.

If you want to make pylint faster for this type of use case, you can use the --errors-only option, which will remove all the refactor, convention, and warning checks. You can also disable checks with inherently high complexity that need to analyse the full code base like duplicate-code or cyclic-import (this list is not exhaustive).

### Pylint version, platform, etc.

Not applicable.

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue. We might add something to the tune of "unless a lot of work is done by your IDE to accommodate pylint", feel free to open a PR to modify the doc here:

https://github.com/pylint-dev/pylint/blob/83cc31c0b0045c7f210f56a7bb8f4339cb02043c/doc/faq.rst?plain=1#L70-L91

**Comment by edreamleo** [comment]
@Pierre-Sassoulas I'll give it a go.
