### ISSUE TITLE
How to silence "Argument of type "None" cannot be assigned to parameter "dtype" of type "DType" in function "__init__"    "None" is not assignable to "DType""

### ISSUE THREAD

**Issue by acampove** [pylint-dev/pylint#9998]
### Question

I am seeing:

```
Argument of type "None" cannot be assigned to parameter "dtype" of type "DType" in function "__init__"    "None" is not assignable to "DType"
```

and it seems to come from a tool I have no control over. How should I silence this?

### Documentation for future user

I googled this and could not find it. Also I searched in the issues of this project

**Comment by Pierre-Sassoulas** [comment]
Intuitively I think it's a pyright message, in any case not a message emitted by pylint.
